// AUTO-GENERATED by scriptengine.Engine.WriteTypes — do not edit by hand.

declare function greet(arg0: string): string;

declare function divide(arg0: number, arg1: number): number;

declare const math: {
  pi: number;
  squared(arg0: number): number;
};

