// AUTO-GENERATED by scriptengine.Engine.WriteTypes — do not edit by hand.

/**
 * sercon's runtime global. Holds the per-script argument vector.
 *
 * Layout mirrors Node/Bun: [programName, scriptPath, ...userArgs].
 * Real arguments (those after `--` on the command line) start at index 2.
 */
declare const Sercon: {
  argv: string[];
};

declare function greet(arg0: string): string;

declare function divide(arg0: number, arg1: number): number;

declare const math: {
  pi: number;
  squared(arg0: number): number;
};

