// AUTO-GENERATED by scriptengine.Engine.WriteTypes — do not edit by hand.
// Reserved globals: demo, divide, greet, math.

// --- ambient types referenced by the binding signatures below ---
type CookieOpts = {
  domain?: string;
  path?: string;
  maxAge?: number;
  expires?: number;
  secure?: boolean;
  httpOnly?: boolean;
  sameSite?: "strict" | "lax" | "none";
};

type WSMessage =
  | { type: "text"; text: string }
  | { type: "binary"; bytes: Uint8Array };

type WebSocket = AsyncIterable<WSMessage> & {
  send(data: string | Uint8Array): Promise<void>;
  close(code?: number, reason?: string): Promise<void>;
  remote: string;
  closeCode?: number;
  closeReason?: string;
};

type SSEStream = {
  send(data: string | { data: unknown; event?: string; id?: string; retry?: number }): Promise<void>;
  close(): Promise<void>;
  readonly closed: Promise<void>;
  readonly remote: string;
};

type Request = {
  method: string;
  url: string;
  path: string;
  query: Record<string, string[]>;
  headers: Record<string, string[]>;
  params: Record<string, string>;
  body: string;
  bodyBytes: Uint8Array;
  remote: string;
  cookies: Record<string, string>;
};

type Response = {
  status(code: number): Response;
  header(name: string, value: string): Response;
  cookie(name: string, value: string, opts?: CookieOpts): Response;
  json(value: unknown): Response;
  text(s: string): Response;
  html(s: string): Response;
  bytes(b: Uint8Array, ct?: string): Response;
  empty(): Response;
  redirect(loc: string, code?: number): Response;
  upgradeWebSocket(opts?: { readBuffer?: number }): Promise<WebSocket>;
  sse(opts?: { keepAlive?: number; retry?: number }): SSEStream;
};

type Envelope = {
  from: string;
  recipients: string[];
  remote: string;
  helo: string;
  authenticatedUser?: string;
  tls?: { version: string; cipher: string };
};

type Message = {
  from: string;
  to: string[];
  cc: string[];
  subject: string;
  headers: Record<string, string[]>;
  body: { text: string; html: string };
  attachments: Array<{ filename: string; contentType: string; bytes: Uint8Array }>;
  raw: Uint8Array;
};

type Pane = {
  write(s: string): void;
  writeln(s: string): void;
  clear(): void;
  title(s: string): void;
};

type Image = {
  readonly width: number;
  readonly height: number;
  readonly format: string;
  resize(w: number, h: number, opts?: { filter?: "lanczos" | "nearest" | "linear" | "box" | "catmullrom" }): Image;
  fit(w: number, h: number): Image;
  thumbnail(w: number, h: number): Image;
  crop(x: number, y: number, w: number, h: number): Image;
  rotate(deg: number): Image;
  rotate90(): Image;
  rotate180(): Image;
  rotate270(): Image;
  flipH(): Image;
  flipV(): Image;
  orient(n: number): Image;
  brightness(pct: number): Image;
  contrast(pct: number): Image;
  saturation(pct: number): Image;
  gamma(g: number): Image;
  sharpen(sigma: number): Image;
  blur(sigma: number): Image;
  grayscale(): Image;
  invert(): Image;
  overlay(other: Image, x: number, y: number, opacity?: number): Image;
  paste(other: Image, x: number, y: number): Image;
  bytes(format: string, opts?: { quality?: number }): Uint8Array;
  save(path: string, opts?: { format?: string; quality?: number }): void;
};

declare function greet(arg0: string): string;

declare function divide(arg0: number, arg1: number): number;

declare const math: {
  pi: number;
  squared(arg0: number): number;
};

declare const demo: {
  /**
   * Hash it.
   * @param input the UTF-8 input
   * @returns string
   */
  hash(input: string): string;
};

