package main

import "github.com/codedeviate/sercon/pkg/scriptengine"

func textDocs() map[string]scriptengine.MemberDoc {
	return map[string]scriptengine.MemberDoc{
		"str.trim": {
			Summary: "Strip whitespace (or any char in the optional mask string) from both ends.",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "The string to trim."},
				{Name: "mask", Type: "string", Optional: true, Desc: "Cutset: any character in this string is trimmed (PHP-style, not a prefix). Defaults to the whitespace set \" \\t\\n\\r\\v\\f\"."},
			},
			ReturnType: "string",
			Returns:    "string — input with leading and trailing mask characters removed.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.trim("  hi  "); // "hi"`,
		},
		"str.ltrim": {
			Summary: "Like trim, left side only.",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "The string to trim."},
				{Name: "mask", Type: "string", Optional: true, Desc: "Cutset of characters to strip from the left. Defaults to the whitespace set \" \\t\\n\\r\\v\\f\"."},
			},
			ReturnType: "string",
			Returns:    "string — input with leading mask characters removed.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.ltrim("--x", "-"); // "x"`,
		},
		"str.rtrim": {
			Summary: "Like trim, right side only.",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "The string to trim."},
				{Name: "mask", Type: "string", Optional: true, Desc: "Cutset of characters to strip from the right. Defaults to the whitespace set \" \\t\\n\\r\\v\\f\"."},
			},
			ReturnType: "string",
			Returns:    "string — input with trailing mask characters removed.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.rtrim("x...", "."); // "x"`,
		},
		"str.reverse": {
			Summary:    "Rune-aware reversal — `reverse('café')` is `'éfac'`.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "The string to reverse. Reversed by Unicode code point, not byte, so multi-byte runes stay intact."}},
			ReturnType: "string",
			Returns:    "string — the input reversed rune-by-rune.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.reverse("café"); // "éfac"`,
		},
		"str.stripHtml": {
			Summary:    "Remove HTML tags and decode common entities.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "HTML source. Anything matching <...> is removed."}},
			ReturnType: "string",
			Returns:    "string — the input with all <...> tag spans deleted.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.stripHtml("<b>hi</b>"); // "hi"`,
		},
		"str.nl2br": {
			Summary: "Replace newlines with <br> (or <br/> when xhtml=true).",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "Source text. CRLF is normalised to LF first, so each line break yields one tag."},
				{Name: "xhtml", Type: "boolean", Optional: true, Desc: "When truthy, emit the self-closing <br/> instead of <br>. Defaults to false."},
			},
			ReturnType: "string",
			Returns:    "string — input with each \\n replaced by the chosen <br> tag followed by the original newline.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.nl2br("a\nb"); // "a<br>\nb"`,
		},
		"str.br2nl": {
			Summary:    "Inverse of nl2br: <br>, <br/>, <br /> → '\\n'.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Source text. Any case-insensitive <br>, <br/>, or <br /> variant is matched."}},
			ReturnType: "string",
			Returns:    "string — input with each <br> variant replaced by a single \\n.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.br2nl("a<br/>b"); // "a\nb"`,
		},
		"str.base64Encode": {
			Summary:    "Standard base64 (with padding).",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "UTF-8 string to encode (encoded as its raw bytes)."}},
			ReturnType: "string",
			Returns:    "string — RFC 4648 standard base64 with `=` padding.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.base64Encode("hi"); // "aGk="`,
		},
		"str.base64Decode": {
			Summary:    "Decode standard (RFC 4648) base64 with padding. The standard alphabet only — URL-safe input (containing `-` or `_`) is NOT auto-detected and will throw; use `base64UrlDecode` for that.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Standard-alphabet base64 string with `=` padding. URL-safe characters (`-`/`_`) are not accepted."}},
			ReturnType: "string",
			Returns:    "string — the decoded bytes interpreted as a UTF-8 string.",
			Errors:     "Throws a TypeError if input is missing/null/undefined; throws if the input is not valid standard base64 (including URL-safe alphabet input).",
			Example:    `text.str.base64Decode("aGk="); // "hi"`,
		},
		"str.base64UrlEncode": {
			Summary:    "URL-safe base64 (RFC 4648 §5: `-`/`_` alphabet), without `=` padding — safe to drop in URLs, filenames, or JWT segments.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "UTF-8 string to encode (encoded as its raw bytes)."}},
			ReturnType: "string",
			Returns:    "string — URL-safe base64 with no padding.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    "text.str.base64UrlEncode(\"a?b\"); // \"YT9i\"",
		},
		"str.base64UrlDecode": {
			Summary:    "Decode URL-safe (RFC 4648 §5) base64. Tolerant of both padded and unpadded input (trailing `=` is optional). Use `base64Decode` for the standard `+`/`/` alphabet.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "URL-safe base64 string (`-`/`_` alphabet); `=` padding optional."}},
			ReturnType: "string",
			Returns:    "string — the decoded bytes interpreted as a UTF-8 string.",
			Errors:     "Throws a TypeError if input is missing/null/undefined; throws if the input is not valid URL-safe base64.",
			Example:    "text.str.base64UrlDecode(\"YT9i\"); // \"a?b\"",
		},
		"str.urlEncode": {
			Summary:    "Form-encoding ('+' for space). For path segments use encodeURIComponent (provided by goja).",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "String to percent-encode. Uses application/x-www-form-urlencoded rules: space becomes `+`."}},
			ReturnType: "string",
			Returns:    "string — the form-encoded value.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.urlEncode("a b&c"); // "a+b%26c"`,
		},
		"str.urlDecode": {
			Summary:    "Inverse of urlEncode.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "A form-encoded string (`+` decodes to space, %XX to bytes)."}},
			ReturnType: "string",
			Returns:    "string — the decoded value.",
			Errors:     "Throws a TypeError if input is missing/null/undefined; throws on malformed percent-escapes.",
			Example:    `text.str.urlDecode("a+b%26c"); // "a b&c"`,
		},
		"str.htmlEntityDecode": {
			Summary:    "Decode named and numeric HTML entities to their UTF-8 equivalents.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Text containing HTML entities (named like &amp; or numeric like &#39; / &#x27;)."}},
			ReturnType: "string",
			Returns:    "string — input with recognised entities decoded to their UTF-8 characters.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.htmlEntityDecode("a &amp; b"); // "a & b"`,
		},
		"str.pad": {
			Summary: "Pad to `len` with `padChar` (default ' '). `side` is 'right' (default), 'left', or 'both'.",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "The string to pad. Returned unchanged when its rune length already meets or exceeds len."},
				{Name: "len", Type: "number", Desc: "Target rune length. Measured in runes, not bytes."},
				{Name: "padChar", Type: "string", Optional: true, Desc: "Pad string; truncated to fit the needed width. Defaults to a single space."},
				{Name: "side", Type: "\"right\" | \"left\" | \"both\"", Optional: true, Desc: "Which side(s) to pad. 'both' splits the deficit with the extra rune going right. Defaults to 'right'; any unknown value is treated as 'right'."},
			},
			ReturnType: "string",
			Returns:    "string — input padded to len runes on the chosen side(s).",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.pad("7", 3, "0", "left"); // "007"`,
		},
		"str.lpad": {
			Summary: "Shortcut for pad(side: 'left').",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "The string to pad on the left."},
				{Name: "len", Type: "number", Desc: "Target rune length."},
				{Name: "padChar", Type: "string", Optional: true, Desc: "Pad string; defaults to a single space."},
			},
			ReturnType: "string",
			Returns:    "string — input left-padded to len runes.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.lpad("7", 3, "0"); // "007"`,
		},
		"str.rpad": {
			Summary: "Shortcut for pad(side: 'right').",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "The string to pad on the right."},
				{Name: "len", Type: "number", Desc: "Target rune length."},
				{Name: "padChar", Type: "string", Optional: true, Desc: "Pad string; defaults to a single space."},
			},
			ReturnType: "string",
			Returns:    "string — input right-padded to len runes.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `text.str.rpad("7", 3, "."); // "7.."`,
		},
		"str.sprintf": {
			Summary: "Go's fmt verbs (%s, %d, %x, %.2f, %v, %t, %q, …) — not PHP's.",
			Params: []scriptengine.Param{
				{Name: "format", Type: "string", Desc: "A Go fmt format string. Uses Go verbs: %s string, %d integer, %f / %.2f float, %x hex, %v default, %t bool, %q quoted, %%  literal percent."},
				{Name: "args", Type: "...unknown", Optional: true, Desc: "Values substituted into the verbs (passed through .Export(), so JS numbers arrive as Go int64/float64)."},
			},
			ReturnType: "string",
			Returns:    "string — the formatted result.",
			Errors:     "Throws a TypeError if called with no arguments (format string required). Verb/arg mismatches are not thrown — Go renders %!verb(...) error markers inline.",
			Example:    `text.str.sprintf("%s=%d", "n", 5); // "n=5"`,
		},
		"str.printf": {
			Summary: "sprintf + write to stdout.",
			Params: []scriptengine.Param{
				{Name: "format", Type: "string", Desc: "A Go fmt format string (same verbs as sprintf)."},
				{Name: "args", Type: "...unknown", Optional: true, Desc: "Values substituted into the verbs."},
			},
			ReturnType: "void",
			Returns:    "void — writes the formatted text directly to process stdout; returns nothing.",
			Errors:     "Throws a TypeError if called with no arguments (format string required).",
			Example:    `text.str.printf("%d items\n", 3);`,
		},
		"str.normalizeNewlines": {
			Summary: "Canonicalise any mix of \\r\\n, \\r, \\n to the requested style ('lf' | 'crlf' | 'cr').",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "Text with any mix of CRLF, CR, and LF line endings."},
				{Name: "style", Type: "\"lf\" | \"crlf\" | \"cr\"", Optional: true, Desc: "Target line-ending style. Defaults to 'lf'."},
			},
			ReturnType: "string",
			Returns:    "string — input with every line ending rewritten to the requested style.",
			Errors:     "Throws a TypeError if style is not one of 'lf', 'crlf', or 'cr'.",
			Example:    `text.str.normalizeNewlines("a\r\nb", "lf"); // "a\nb"`,
		},
		"charset.detect": {
			Summary:    "Detect the most-likely charset of a byte sequence (saintfish/chardet). Resolves to the top guess plus the full candidate list, each scored 0–100.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string | Uint8Array | ArrayBuffer", Desc: "Bytes to sniff. A string is taken as its raw UTF-8 bytes."}},
			ReturnType: "Promise<{ charset: string; confidence: number; language?: string; candidates: { charset: string; confidence: number; language?: string }[] }>",
			Returns:    "Promise<{ charset, confidence, language?, candidates }> — the top match plus all candidates; confidence is chardet's 0–100 score. language is present only when chardet reports one.",
			Errors:     "Rejects if input is empty, an unsupported type, or chardet finds no candidates.",
			Example: `const r = await text.charset.detect(bytes);
runtime.log(r.charset, r.confidence);`,
		},
		"charset.decode": {
			Summary: "Decode bytes in a named charset to a UTF-8 string.",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string | Uint8Array | ArrayBuffer", Desc: "Bytes encoded in `charset`."},
				{Name: "charset", Type: "string", Desc: "WHATWG/HTML5 encoding name or alias (UTF-8, ISO-8859-1, Windows-1252, Shift_JIS, GBK, …)."},
			},
			ReturnType: "Promise<string>",
			Returns:    "Promise<string> — the bytes decoded to a UTF-8 string.",
			Errors:     "Rejects if input is an unsupported type, the charset name is unknown, or the bytes are invalid for that encoding.",
			Example:    `const s = await text.charset.decode(bytes, "Windows-1252");`,
		},
		"charset.encode": {
			Summary: "Encode a UTF-8 string to bytes in the named charset.",
			Params: []scriptengine.Param{
				{Name: "input", Type: "string", Desc: "UTF-8 string to encode."},
				{Name: "charset", Type: "string", Desc: "Target WHATWG/HTML5 encoding name or alias."},
			},
			ReturnType: "Promise<Uint8Array>",
			Returns:    "Promise<Uint8Array> — the string encoded as bytes in the target charset.",
			Errors:     "Rejects if the charset name is unknown, or a character has no representation in the target encoding (no lossy fallback — characters are not silently dropped).",
			Example:    `const bytes = await text.charset.encode("café", "ISO-8859-1");`,
		},
		"preg.match": {
			Summary: "First hit of /pattern/flags against subject, or null. Returns { match, groups, index }; optional groups that didn't match surface as empty strings.",
			Params: []scriptengine.Param{
				{Name: "pattern", Type: "string", Desc: "A PHP-style /regex/flags delimited pattern (forward-slash delimiter only). Engine is Go RE2. Flags: i (case-insensitive), m (multiline ^/$), s (dotall). u/U/x are rejected."},
				{Name: "subject", Type: "string", Desc: "The string to search."},
			},
			ReturnType: "{ match: string; groups: string[]; index: number } | null",
			Returns:    "{ match, groups, index } for the first match, where match is the full match, groups holds the numbered submatches after group 0 (unmatched optionals as \"\"), and index is the byte offset; null when there is no match.",
			Errors:     "Throws if the pattern is empty, lacks a leading/closing `/`, uses an unsupported flag (u/U/x), or fails RE2 compilation (e.g. backreferences/lookaround, which RE2 does not support).",
			Example:    `const m = text.preg.match("/(\\d+)/", "x42"); // { match: "42", groups: ["42"], index: 1 }`,
		},
		"preg.matchAll": {
			Summary: "Every hit of /pattern/flags against subject, as an array of { match, groups, index } objects.",
			Params: []scriptengine.Param{
				{Name: "pattern", Type: "string", Desc: "A PHP-style /regex/flags delimited pattern (RE2 engine; i/m/s flags)."},
				{Name: "subject", Type: "string", Desc: "The string to search."},
			},
			ReturnType: "{ match: string; groups: string[]; index: number }[]",
			Returns:    "Array of { match, groups, index } objects, one per non-overlapping match; empty array when there is none.",
			Errors:     "Throws on the same conditions as preg.match (bad delimiter, unsupported flag, RE2 compile failure).",
			Example:    `const all = text.preg.matchAll("/\\d+/", "1 22 333"); // 3 matches`,
		},
		"preg.replace": {
			Summary: "Substitute every match of /pattern/flags in subject. Replacement uses Go's $1 / ${1} backref syntax — PHP's \\1 form is NOT translated.",
			Params: []scriptengine.Param{
				{Name: "pattern", Type: "string", Desc: "A PHP-style /regex/flags delimited pattern (RE2 engine; i/m/s flags)."},
				{Name: "replacement", Type: "string", Desc: "Replacement template using Go's RE2 syntax: $1 / ${name} reference groups; use ${1} to disambiguate. PHP's \\1 backrefs are NOT supported."},
				{Name: "subject", Type: "string", Desc: "The string to transform."},
			},
			ReturnType: "string",
			Returns:    "string — subject with every match replaced (all occurrences).",
			Errors:     "Throws on the same conditions as preg.match (bad delimiter, unsupported flag, RE2 compile failure).",
			Example:    `text.preg.replace("/(\\w+)@/", "${1}_at_", "a@b"); // "a_at_b"`,
		},
		"preg2.match": {
			Summary: "First hit of /pattern/flags via regexp2 (PCRE). Supports lookahead/lookbehind/backreferences. Same { match, groups, index } shape as preg. No linear-time guarantee.",
			Params: []scriptengine.Param{
				{Name: "pattern", Type: "string", Desc: "A /regex/flags delimited pattern run on the .NET-flavoured regexp2 engine (lookaround, backreferences, possessive quantifiers). Flags: i, m, s, and x (ignore-pattern-whitespace, unavailable in preg). u/U are rejected."},
				{Name: "subject", Type: "string", Desc: "The string to search."},
			},
			ReturnType: "{ match: string; groups: string[]; index: number } | null",
			Returns:    "{ match, groups, index } for the first match (same shape as preg.match); null when there is no match.",
			Errors:     "Throws if the pattern is empty, lacks a leading/closing `/`, uses an unsupported flag (u/U), fails regexp2 compilation, or errors during matching. Backtracking engine: guard untrusted input with a timeout.",
			Example:    `const m = text.preg2.match("/(?<=@)\\w+/", "a@host"); // { match: "host", ... }`,
		},
		"preg2.matchAll": {
			Summary: "Every hit of /pattern/flags via regexp2 (PCRE), as an array of { match, groups, index }.",
			Params: []scriptengine.Param{
				{Name: "pattern", Type: "string", Desc: "A /regex/flags delimited pattern on the regexp2 engine (i/m/s/x flags)."},
				{Name: "subject", Type: "string", Desc: "The string to search."},
			},
			ReturnType: "{ match: string; groups: string[]; index: number }[]",
			Returns:    "Array of { match, groups, index } objects, one per match; empty array when there is none.",
			Errors:     "Throws on the same conditions as preg2.match. Backtracking engine: guard untrusted input with a timeout.",
			Example:    `const all = text.preg2.matchAll("/\\w+/", "a b c"); // 3 matches`,
		},
		"preg2.replace": {
			Summary: "Substitute every match of /pattern/flags via regexp2. Replacement uses .NET $1 / ${1} syntax. Backtracking engine — keep a timeout around untrusted input.",
			Params: []scriptengine.Param{
				{Name: "pattern", Type: "string", Desc: "A /regex/flags delimited pattern on the regexp2 engine (i/m/s/x flags)."},
				{Name: "replacement", Type: "string", Desc: "Replacement template using .NET substitution syntax: $1 / ${1} reference groups, $$ is a literal dollar."},
				{Name: "subject", Type: "string", Desc: "The string to transform."},
			},
			ReturnType: "string",
			Returns:    "string — subject with every match replaced (startAt 0, count -1).",
			Errors:     "Throws on the same conditions as preg2.match, or if replacement fails. Backtracking engine: guard untrusted input with a timeout.",
			Example:    `text.preg2.replace("/(\\w)\\1/", "X", "aabb"); // backref-aware: "XX"`,
		},
		"jq.query": {
			Summary: "Run a jq filter over data and return the first emitted value (or null).",
			Params: []scriptengine.Param{
				{Name: "data", Type: "unknown", Desc: "Input value — any JSON-like JS value (object/array/scalar). Passed to gojq directly; integers of any width are normalised so queries don't blow up."},
				{Name: "filter", Type: "string", Desc: "A jq filter expression, e.g. \".users[0].name\" or \".items | length\"."},
			},
			ReturnType: "Promise<unknown>",
			Returns:    "Promise<unknown> — the first value the filter emits, or null when it emits nothing (e.g. an optional path like .a.b? that misses).",
			Errors:     "Rejects if data is undefined, the filter string is empty, the filter fails to parse, or evaluation produces an error.",
			Example:    `const name = await text.jq.query(obj, ".users[0].name");`,
		},
		"jq.queryAll": {
			Summary: "Run a jq filter and drain the iterator into an array.",
			Params: []scriptengine.Param{
				{Name: "data", Type: "unknown", Desc: "Input value — any JSON-like JS value."},
				{Name: "filter", Type: "string", Desc: "A jq filter expression. Use this when the filter explodes a stream, e.g. \".[]\" or \".users[].id\"."},
			},
			ReturnType: "Promise<unknown[]>",
			Returns:    "Promise<unknown[]> — every value the filter emits, in order (empty array when it emits nothing).",
			Errors:     "Rejects if data is undefined, the filter string is empty, the filter fails to parse, or evaluation produces an error.",
			Example:    `const ids = await text.jq.queryAll(obj, ".users[].id");`,
		},
		"stego.embed": {
			Summary: "Hide a payload inside cover text using zero-width characters (U+200B / U+200C), appended as an invisible trailing run — the visible text is unchanged. A non-empty password encrypts the payload (AES-256-GCM). Returns the cover text with the hidden run.",
			Params: []scriptengine.Param{
				{Name: "cover", Type: "string", Desc: "The visible cover text."},
				{Name: "payload", Type: "string | Uint8Array", Desc: "Data to hide. A string is stored as UTF-8 text (extract returns a string); a Uint8Array is stored as binary."},
				{Name: "opts", Type: "{ password?: string }", Optional: true, Desc: "password encrypts the payload with AES-256-GCM."},
			},
			ReturnType: "string",
			Returns:    "The cover text followed by the invisible zero-width payload run.",
			Errors:     "Throws a TypeError if payload is neither a string nor Uint8Array.",
			Example:    `const out = text.stego.embed("Hello there.", "meet at noon", { password: "s3cret" });`,
		},
		"stego.extract": {
			Summary: "Recover a payload hidden by text.stego.embed. Scans the string for zero-width carrier characters, verifies the sercon header, and returns the payload as a string (if embedded as text) or a Uint8Array. There is no capacity() for text — the hidden run is appended, so capacity is effectively unbounded.",
			Params: []scriptengine.Param{
				{Name: "stegoText", Type: "string", Desc: "Text produced by text.stego.embed (or a copy that preserved the zero-width characters)."},
				{Name: "opts", Type: "{ password?: string }", Optional: true, Desc: "The password used at embed time, required when the payload was encrypted."},
			},
			ReturnType: "string | Uint8Array",
			Returns:    "The recovered payload — a string when embedded as text, otherwise a Uint8Array.",
			Errors:     "Throws if no sercon stego payload is present, if the payload is encrypted but no password is given, or if decryption fails (wrong password / corrupt).",
			Example:    `const msg = text.stego.extract(out, { password: "s3cret" });`,
		},
		"diff.compare": {
			Summary: "Unified-diff two text inputs. opts: context (default 3), fromFile / toFile (default 'a' / 'b'). Binary inputs return { binary: true } with an empty diff.",
			Params: []scriptengine.Param{
				{Name: "a", Type: "string | Uint8Array | ArrayBuffer", Desc: "The 'from' / left side. A string is taken as its UTF-8 bytes."},
				{Name: "b", Type: "string | Uint8Array | ArrayBuffer", Desc: "The 'to' / right side."},
				{Name: "opts", Type: "{ context?: number; fromFile?: string; toFile?: string }", Optional: true, Desc: "context is the number of unchanged lines around each hunk (default 3); fromFile / toFile are the header labels (default 'a' / 'b')."},
			},
			ReturnType: "Promise<{ identical: boolean; binary: boolean; added: number; removed: number; diff: string; format: \"unified\" }>",
			Returns:    "Promise<{ identical, binary, added, removed, diff, format }> — diff holds the unified-diff text (empty when identical or binary); added/removed count body +/- lines excluding file headers; binary is true when either input has a NUL byte in its first 8 KB.",
			Errors:     "Rejects if either input is an unsupported type, or the unified-diff generation fails.",
			Example: `const d = await text.diff.compare("a\n", "b\n");
runtime.log(d.diff, d.added, d.removed);`,
		},
	}
}
