package main

import "github.com/codedeviate/sercon/pkg/scriptengine"

func cryptoDocs() map[string]scriptengine.MemberDoc {
	return map[string]scriptengine.MemberDoc{
		"hash.md5": {
			Summary:    "MD5 hex digest of a UTF-8 input. Avoid for security purposes — exposed for compatibility with legacy fingerprints.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to hash, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 32-char lowercase hex digest.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const d = crypto.hash.md5("hello"); // "5d41402abc4b2a76b9719d911017c592"`,
		},
		"hash.sha1": {
			Summary:    "SHA-1 hex digest of a UTF-8 input. Avoid for security purposes.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to hash, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 40-char lowercase hex digest.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const d = crypto.hash.sha1("hello");`,
		},
		"hash.sha256": {
			Summary:    "SHA-256 hex digest of a UTF-8 input.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to hash, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 64-char lowercase hex digest.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const d = crypto.hash.sha256("hello");`,
		},
		"hash.sha384": {
			Summary:    "SHA-384 hex digest of a UTF-8 input.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to hash, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 96-char lowercase hex digest.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const d = crypto.hash.sha384("hello");`,
		},
		"hash.sha512": {
			Summary:    "SHA-512 hex digest of a UTF-8 input.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to hash, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 128-char lowercase hex digest.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const d = crypto.hash.sha512("hello");`,
		},
		"hash.sha3_256": {
			Summary:    "SHA-3 256-bit hex digest. The underscore in the name matches recon's binding.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to hash, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 64-char lowercase hex digest.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const d = crypto.hash.sha3_256("hello");`,
		},
		"hash.sha3_512": {
			Summary:    "SHA-3 512-bit hex digest.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to hash, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 128-char lowercase hex digest.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const d = crypto.hash.sha3_512("hello");`,
		},
		"hash.blake3": {
			Summary:    "BLAKE3 hex digest (32-byte output, lukechampine.com/blake3).",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to hash, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 64-char lowercase hex digest (256-bit output).",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const d = crypto.hash.blake3("hello");`,
		},
		"hash.crc32": {
			Summary:    "CRC-32 (IEEE polynomial), zero-padded to 8 hex chars.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "Data to checksum, interpreted as a UTF-8 byte sequence."}},
			ReturnType: "string",
			Returns:    "string — 8-char zero-padded lowercase hex checksum.",
			Errors:     "Throws a TypeError if input is missing, null, or undefined.",
			Example:    `const c = crypto.hash.crc32("hello"); // "3610a686"`,
		},
		"jwt.sign": {
			Summary: "Sign a claims object. secret is raw bytes for HS*; PEM-encoded private key for RS*/PS*/ES*/EdDSA; or a JWK JSON object (kty picks the key type) for any algorithm. opts.algorithm defaults to HS256.",
			Params: []scriptengine.Param{
				{Name: "claims", Type: "Record<string, unknown>", Desc: "Claims payload. Passed through to MapClaims; RFC 7519 reserved claims (exp/nbf/iat/iss/aud/sub) are honoured. Reserved claims are NOT synthesised — set iat/exp explicitly if you want them."},
				{Name: "secret", Type: "string", Desc: "Key material: raw HMAC bytes for HS256/384/512, a PEM-encoded private key (-----BEGIN ...) for RS*/PS*/ES*/EdDSA, or a JWK JSON object ({\"kty\":...})."},
				{Name: "opts", Type: "{ algorithm?: string }", Optional: true, Desc: "algorithm names the RFC 7518 alg (HS256/HS384/HS512, RS256/384/512, PS256/384/512, ES256/384/512, EdDSA); case-insensitive. Defaults to HS256."},
			},
			ReturnType: "string",
			Returns:    "string — the signed compact-serialisation JWT (header.payload.signature).",
			Errors:     "Throws if claims is null, secret is empty, the algorithm is unsupported, or the secret shape mismatches the algorithm (e.g. HMAC algo with a PEM key, or asymmetric algo with plain bytes).",
			Example:    `const tok = crypto.jwt.sign({ sub: "u1" }, "topsecret", { algorithm: "HS256" });`,
		},
		"jwt.view": {
			Summary:    "Decode header + payload WITHOUT verifying the signature. Useful for inspection / debugging auth flows. Malformed input throws.",
			Params:     []scriptengine.Param{{Name: "token", Type: "string", Desc: "A compact-serialisation JWT (three dot-separated base64url segments)."}},
			ReturnType: "{ header: object; payload: object; signature: string }",
			Returns:    "{ header: object, payload: object, signature: string } — decoded header and payload (object key order preserved) plus the raw signature segment.",
			Errors:     "Throws if the token is not three dot-separated segments or a segment fails base64url / JSON decoding.",
			Example:    `const { header, payload } = crypto.jwt.view(tok);`,
		},
		"jwt.validate": {
			Summary: "Verify signature + standard claims (exp/nbf/iat) + optional aud/iss. secret accepts raw bytes / PEM public key / JWK. Set opts.algorithm for the algo-confusion guard. Resolves { valid:true, claims } or { valid:false, reason }.",
			Params: []scriptengine.Param{
				{Name: "token", Type: "string", Desc: "The compact-serialisation JWT to verify."},
				{Name: "secret", Type: "string", Desc: "Verification key: raw HMAC bytes, a PEM-encoded public key (or certificate), or a JWK JSON object."},
				{Name: "opts", Type: "{ algorithm?: string, audience?: string, issuer?: string }", Optional: true, Desc: "algorithm pins the accepted alg (algorithm-confusion guard); when unset, any supported alg is accepted. audience / issuer enforce the aud / iss claims when set."},
			},
			ReturnType: "{ valid: boolean; claims?: object; reason?: string }",
			Returns:    "{ valid: true, claims: object } on success, or { valid: false, reason: string } on any verification / claim failure.",
			Errors:     "Throws only on structural / wiring errors (empty token or secret, malformed token, or a secret shape that mismatches the token's algorithm). Cryptographic and claim failures resolve as { valid: false, reason } instead of throwing.",
			Example: `const r = crypto.jwt.validate(tok, "topsecret", { algorithm: "HS256" });
if (r.valid) runtime.log(r.claims.sub);`,
		},
		"encrypt.keygen": {
			Summary:    "Generate a fresh age X25519 keypair. Returns { publicKey: 'age1...', privateKey: 'AGE-SECRET-KEY-1...' }.",
			ReturnType: "{ publicKey: string; privateKey: string }",
			Returns:    "{ publicKey: string, privateKey: string } — publicKey is the shareable age1... recipient; privateKey is the secret AGE-SECRET-KEY-1... identity.",
			Errors:     "Throws if the system RNG fails to generate an identity.",
			Example:    `const { publicKey, privateKey } = crypto.encrypt.keygen();`,
		},
		"encrypt.keygenPgp": {
			Summary: "Generate a PGP keypair (RSA 2048). opts.name / opts.email populate the user ID. Returns armored { publicKey, privateKey } blocks. encrypt/decrypt auto-route to PGP when they see these.",
			Params: []scriptengine.Param{
				{Name: "opts", Type: "{ name?: string, email?: string }", Optional: true, Desc: "name and email populate the primary user ID; both default to empty (fine for throwaway keys)."},
			},
			ReturnType: "{ publicKey: string; privateKey: string }",
			Returns:    "{ publicKey: string, privateKey: string } — both ASCII-armored PGP key blocks (-----BEGIN PGP PUBLIC/PRIVATE KEY BLOCK-----).",
			Errors:     "Throws if entity generation or armor serialisation fails.",
			Example:    `const { publicKey, privateKey } = crypto.encrypt.keygenPgp({ name: "Test", email: "t@example.com" });`,
		},
		"encrypt.encrypt": {
			Summary: "Seal data to recipients. age public keys (age1...) → age backend (opts.armored for ASCII); PGP public-key blocks → PGP backend (always armored). Auto-dispatched on key format. Multi-recipient: any listed identity decrypts.",
			Params: []scriptengine.Param{
				{Name: "data", Type: "string | Uint8Array | ArrayBuffer", Desc: "Plaintext to encrypt."},
				{Name: "recipients", Type: "string | string[]", Desc: "One or more recipient public keys. age1... bech32 keys use the age backend; -----BEGIN PGP PUBLIC KEY BLOCK----- entries use the PGP backend. Backends cannot be mixed in one call."},
				{Name: "opts", Type: "{ armored?: boolean }", Optional: true, Desc: "armored (age backend only) wraps the output in age ASCII armor; defaults to false (binary). Ignored on the PGP path, which is always armored."},
			},
			ReturnType: "Uint8Array",
			Returns:    "Uint8Array — the ciphertext (binary age, ASCII-armored age when opts.armored, or armored PGP message bytes).",
			Errors:     "Throws if data is an unsupported type, no recipients are given, a recipient is actually a private key, or a recipient string fails to parse.",
			Example:    `const ct = crypto.encrypt.encrypt("secret", publicKey, { armored: true });`,
		},
		"encrypt.decrypt": {
			Summary: "Open a payload with one of the supplied identities. Routes to age or PGP based on the identity / ciphertext format. age: binary or armored auto-detected. Wrong identity throws.",
			Params: []scriptengine.Param{
				{Name: "ciphertext", Type: "string | Uint8Array | ArrayBuffer", Desc: "The encrypted payload; age armor and PGP armor are auto-detected."},
				{Name: "identities", Type: "string | string[]", Desc: "One or more private keys. AGE-SECRET-KEY-1... identities use the age backend; -----BEGIN PGP PRIVATE KEY BLOCK----- entries (or an armored PGP message) use the PGP backend."},
			},
			ReturnType: "Uint8Array",
			Returns:    "Uint8Array — the decrypted plaintext bytes (decode with new TextDecoder().decode(...) for a string).",
			Errors:     "Throws if ciphertext is empty or an unsupported type, no identities are given, an identity is actually a public key, or no supplied identity matches the ciphertext's recipients.",
			Example: `const pt = crypto.encrypt.decrypt(ct, privateKey);
const text = new TextDecoder().decode(pt);`,
		},
		"encrypt.rekey": {
			Summary: "Re-encrypt for a new recipient set without exposing plaintext to JS. Output format defaults to match the input; opts.armored forces. Internal decrypt+encrypt loop.",
			Params: []scriptengine.Param{
				{Name: "ciphertext", Type: "string | Uint8Array | ArrayBuffer", Desc: "The existing age ciphertext to re-key (armor auto-detected)."},
				{Name: "oldIdentities", Type: "string | string[]", Desc: "Current AGE-SECRET-KEY-1... private keys used to decrypt the existing ciphertext."},
				{Name: "newRecipients", Type: "string | string[]", Desc: "New age1... public keys to encrypt the result for."},
				{Name: "opts", Type: "{ armored?: boolean }", Optional: true, Desc: "armored forces the output armor state; default preserves the input's armor state."},
			},
			ReturnType: "Uint8Array",
			Returns:    "Uint8Array — the re-encrypted ciphertext for the new recipient set.",
			Errors:     "Throws if ciphertext is empty, either key list is empty, a key is the wrong kind (public vs private), or the decrypt step fails (no matching identity / malformed input). age backend only.",
			Example:    `const rotated = crypto.encrypt.rekey(ct, oldKey, newPublicKey);`,
		},
		"encrypt.detectBackend": {
			Summary:    "Classify a recipient / identity string. Returns { backend: 'age'|'pgp'|'unknown', kind?: 'public'|'private' }. Pure prefix matching; no parsing or I/O.",
			Params:     []scriptengine.Param{{Name: "input", Type: "string", Desc: "A recipient or identity string to classify (age bech32, age SSH public key, or PGP armored block)."}},
			ReturnType: "{ backend: string; kind?: string }",
			Returns:    "{ backend: \"age\" | \"pgp\" | \"unknown\", kind?: \"public\" | \"private\" } — kind is present only when the backend was identified.",
			Errors:     "Never throws; unrecognised input returns { backend: \"unknown\" }.",
			Example:    `const info = crypto.encrypt.detectBackend("age1abc..."); // { backend: "age", kind: "public" }`,
		},
	}
}
