package scriptengine

import (
	"io"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// WriteReference emits a deterministic markdown reference of the registered
// surface. It walks the same registrations as WriteTypes / writeDTS so the
// reference structure mirrors the generated .d.ts: one `### <name>` section
// per top-level registration (sorted), and within each, a `#### <dotted.path>`
// entry per member (sorted by dotted path). Headings are unnumbered; see
// WriteReferenceNumbered for hierarchical section numbers.
//
// Each member entry carries a fenced signature line, the MemberDoc Summary as
// a paragraph, and — when present — a Parameters bullet list, a Returns line,
// a Throws line, and an Example fenced block. Empty sections are omitted so
// the output stays compact and byte-stable across regenerations.
func (e *Engine) WriteReference(w io.Writer) error {
	return e.WriteReferenceNumbered(w, "")
}

// WriteReferenceNumbered is WriteReference with hierarchical section numbers.
// When sectionPrefix is non-empty (e.g. "17"), namespace headings become
// `### <prefix>.<N> <name>` and member headings `#### <prefix>.<N>.<M> <path>`,
// so the generated reference matches a numbered manual chapter. An empty
// sectionPrefix reproduces WriteReference's unnumbered output exactly.
func (e *Engine) WriteReferenceNumbered(w io.Writer, sectionPrefix string) error {
	e.regMu.RLock()
	defer e.regMu.RUnlock()
	return writeReference(w, e.registrations, e.docs, sectionPrefix)
}

func writeReference(w io.Writer, regs []registration, docs map[string]MemberDoc, sectionPrefix string) error {
	bw := &errWriter{w: w}
	bw.WriteString("<!-- AUTO-GENERATED by scriptengine.Engine.WriteReference — do not edit by hand. -->\n")

	// Stable top-level ordering, mirroring writeDTS.
	sorted := make([]registration, len(regs))
	copy(sorted, regs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].name < sorted[j].name })

	for i, reg := range sorted {
		// nsNum is the namespace's section number ("" when unnumbered).
		nsNum := ""
		if sectionPrefix != "" {
			nsNum = sectionPrefix + "." + strconv.Itoa(i+1)
		}
		bw.WriteString("\n### " + numberedHeading(nsNum, reg.name) + "\n")
		doc := docs[reg.name]
		mem := 0 // per-namespace member counter for #### numbering
		switch reg.kind {
		case regNamespace:
			// A namespace is a container, not a callable — render its summary
			// as the section intro (no signature fence), then its members.
			if s := strings.TrimSpace(doc.Summary); s != "" {
				bw.WriteString("\n" + s + "\n")
			}
			members := reg.members
			if m, ok := reg.value.(namespaceFactoryMarker); ok && members == nil {
				members = introspectNamespaceFactory(m)
			}
			writeReferenceMembers(bw, members, reg.name, docs, nsNum, &mem)
		case regValue, regConstructor:
			// A top-level value/constructor IS callable — full entry with a
			// signature.
			writeReferenceEntry(bw, memberNum(nsNum, &mem), reg.name, reg.name, doc, topLevelSig(reg, doc))
		}
	}
	return bw.err
}

// numberedHeading prefixes title with num and a space when num is non-empty.
func numberedHeading(num, title string) string {
	if num == "" {
		return title
	}
	return num + " " + title
}

// memberNum advances the per-namespace member counter and returns the next
// member section number ("" when nsNum is empty / unnumbered).
func memberNum(nsNum string, mem *int) string {
	*mem++
	if nsNum == "" {
		return ""
	}
	return nsNum + "." + strconv.Itoa(*mem)
}

// introspectNamespaceFactory calls a namespace factory with nil vm/loop to
// recover its member map, mirroring writeDTS. Factory bodies build their map
// without dereferencing the arguments, but a panic is contained so a single
// misbehaving factory can't abort the whole reference.
func introspectNamespaceFactory(m namespaceFactoryMarker) (members map[string]any) {
	defer func() {
		if r := recover(); r != nil {
			members = nil
		}
	}()
	return m.fn(nil, nil)
}

// writeReferenceMembers walks a namespace's members in sorted dotted-path
// order, descending into nested namespace maps. `path` is the dotted prefix
// used for both headings and doc lookup, matching writeMemberObject.
func writeReferenceMembers(w *errWriter, members map[string]any, path string, docs map[string]MemberDoc, nsNum string, mem *int) {
	keys := make([]string, 0, len(members))
	for k := range members {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		v := members[k]
		memberPath := path + "." + k
		if nested, ok := v.(map[string]any); ok {
			// A nested sub-namespace is a container too: if documented, emit a
			// heading + summary paragraph (no signature fence), then recurse.
			if doc, ok := docs[memberPath]; ok {
				if s := strings.TrimSpace(doc.Summary); s != "" {
					w.WriteString("\n#### " + numberedHeading(memberNum(nsNum, mem), memberPath) + "\n\n" + s + "\n")
				}
			}
			writeReferenceMembers(w, nested, memberPath, docs, nsNum, mem)
			continue
		}
		doc := docs[memberPath]
		writeReferenceEntry(w, memberNum(nsNum, mem), memberPath, k, doc, sigForMember(k, v, doc))
	}
}

// writeReferenceEntry emits a single `#### <num> <path>` section: a fenced
// signature, the Summary paragraph, Parameters, Returns, Throws, and Example —
// omitting every empty section. num is "" for unnumbered output.
func writeReferenceEntry(w *errWriter, num, path, name string, doc MemberDoc, signature string) {
	w.WriteString("\n#### " + numberedHeading(num, path) + "\n")
	w.WriteString("\n```\n" + signature + "\n```\n")

	if s := strings.TrimSpace(doc.Summary); s != "" {
		w.WriteString("\n" + s + "\n")
	}

	if len(doc.Params) > 0 {
		w.WriteString("\n**Parameters**\n\n")
		for _, p := range doc.Params {
			typ := p.Type
			if typ == "" {
				typ = "unknown"
			}
			if p.Optional {
				typ += ", optional"
			}
			line := "- `" + p.Name + "` *(" + typ + ")*"
			if d := strings.TrimSpace(p.Desc); d != "" {
				line += " — " + d
			}
			w.WriteString(line + "\n")
		}
	}

	if r := strings.TrimSpace(doc.Returns); r != "" {
		w.WriteString("\n**Returns:** " + r + "\n")
	}
	if errs := strings.TrimSpace(doc.Errors); errs != "" {
		w.WriteString("\n**Throws:** " + errs + "\n")
	}
	if ex := strings.TrimSpace(doc.Example); ex != "" {
		w.WriteString("\n```ts\n" + ex + "\n```\n")
	}
}

// topLevelSig builds the signature line for a top-level registration. When the
// MemberDoc has Params it uses sigFromParams; otherwise it falls back to a
// reflected/`(...)` form consistent with the d.ts emitter.
func topLevelSig(reg registration, doc MemberDoc) string {
	if reg.kind == regNamespace {
		return reg.name
	}
	value := reg.value
	if m, ok := value.(factoryMarker); ok {
		value = introspectValueFactory(m)
	}
	return sigForMember(reg.name, value, doc)
}

func introspectValueFactory(m factoryMarker) (value any) {
	defer func() {
		if r := recover(); r != nil {
			value = nil
		}
	}()
	return m.fn(nil, nil)
}

// sigForMember produces the fenced signature text for a member. With Params it
// reuses sigFromParams (Param types, no deep type recursion). Without Params it
// reflects a simple `name(...)` form, keeping it consistent and shallow.
func sigForMember(name string, v any, doc MemberDoc) string {
	if a, ok := v.(AsyncBinding); ok {
		ret := asyncReturnType(doc, a)
		if len(doc.Params) > 0 {
			return name + sigFromParams(doc.Params, ret)
		}
		return name + "(...args: unknown[]): " + ret
	}
	t := reflect.TypeOf(v)
	isFunc := t != nil && t.Kind() == reflect.Func
	if isFunc {
		// Callable member: a documented signature (Params and/or ReturnType)
		// or the reflected `(...args)` fallback.
		if len(doc.Params) > 0 || doc.ReturnType != "" {
			ret := doc.ReturnType
			if ret == "" {
				ret = "void"
			}
			return name + sigFromParams(doc.Params, ret)
		}
		return name + "(...args: unknown[])"
	}
	// Non-callable value (e.g. runtime.argv): render as a property, matching
	// the d.ts (`argv: string[]`), not a call.
	if doc.ReturnType != "" {
		return name + ": " + doc.ReturnType
	}
	return name
}
