package scriptengine

import (
	"io"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// WriteReference emits a deterministic markdown reference of the registered
// surface. It walks the same registrations as WriteTypes / writeDTS so the
// reference structure mirrors the generated .d.ts: one `### <name>` section
// per top-level registration (sorted), and within each, a `#### <dotted.path>`
// entry per member (sorted by dotted path). Headings are unnumbered; see
// WriteReferenceNumbered for hierarchical section numbers.
//
// Each member entry carries a fenced signature line, the MemberDoc Summary as
// a paragraph, and — when present — a Parameters bullet list, a Returns line,
// a Throws line, and an Example fenced block. Empty sections are omitted so
// the output stays compact and byte-stable across regenerations.
func (e *Engine) WriteReference(w io.Writer) error {
	return e.WriteReferenceNumbered(w, "")
}

// WriteReferenceNumbered is WriteReference with hierarchical section numbers.
// When sectionPrefix is non-empty (e.g. "17"), namespace headings become
// `### <prefix>.<N> <name>` and member headings `#### <prefix>.<N>.<M> <path>`,
// so the generated reference matches a numbered manual chapter. An empty
// sectionPrefix reproduces WriteReference's unnumbered output exactly.
func (e *Engine) WriteReferenceNumbered(w io.Writer, sectionPrefix string) error {
	e.regMu.RLock()
	defer e.regMu.RUnlock()
	return writeReference(w, e.registrations, e.docs, sectionPrefix)
}

func writeReference(w io.Writer, regs []registration, docs map[string]MemberDoc, sectionPrefix string) error {
	bw := &errWriter{w: w}
	bw.WriteString("<!-- AUTO-GENERATED by scriptengine.Engine.WriteReference — do not edit by hand. -->\n")

	// Stable top-level ordering, mirroring writeDTS.
	sorted := make([]registration, len(regs))
	copy(sorted, regs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].name < sorted[j].name })

	for i, reg := range sorted {
		// nsNum is the namespace's section number ("" when unnumbered).
		nsNum := ""
		if sectionPrefix != "" {
			nsNum = sectionPrefix + "." + strconv.Itoa(i+1)
		}
		bw.WriteString("\n### " + numberedHeading(nsNum, reg.name) + "\n")
		doc := docs[reg.name]
		switch reg.kind {
		case regNamespace:
			// A namespace is a container, not a callable — render its summary
			// as the section intro (no signature fence), then its members as a
			// hierarchical tree (numbers and heading levels track dotted depth).
			if s := strings.TrimSpace(doc.Summary); s != "" {
				bw.WriteString("\n" + s + "\n")
			}
			members := reg.members
			if m, ok := reg.value.(namespaceFactoryMarker); ok && members == nil {
				members = introspectNamespaceFactory(m)
			}
			emitNamespaceTree(bw, members, reg.name, docs, nsNum)
		case regValue, regConstructor:
			// A top-level value/constructor IS callable — full entry with a
			// signature, rendered one level below the namespace heading (H4).
			mem := 0
			writeReferenceEntry(bw, 4, memberNum(nsNum, &mem), reg.name, doc, topLevelSig(reg, doc), true)
		}
	}
	return bw.err
}

// numberedHeading prefixes title with num and a space when num is non-empty.
func numberedHeading(num, title string) string {
	if num == "" {
		return title
	}
	return num + " " + title
}

// memberNum advances the per-namespace member counter and returns the next
// member section number ("" when nsNum is empty / unnumbered).
func memberNum(nsNum string, mem *int) string {
	*mem++
	if nsNum == "" {
		return ""
	}
	return nsNum + "." + strconv.Itoa(*mem)
}

// introspectNamespaceFactory calls a namespace factory with nil vm/loop to
// recover its member map, mirroring writeDTS. Factory bodies build their map
// without dereferencing the arguments, but a panic is contained so a single
// misbehaving factory can't abort the whole reference.
func introspectNamespaceFactory(m namespaceFactoryMarker) (members map[string]any) {
	defer func() {
		if r := recover(); r != nil {
			members = nil
		}
	}()
	return m.fn(nil, nil)
}

// refNode is one node in a namespace's reference tree. A node may correspond to
// a member reachable by the surface walk (hasValue) and/or a member documented
// only via a doc-map key (for runtime-built handles the walk can't introspect,
// e.g. the cloud.<provider> services/methods). Children are merged from nested
// surface maps and nested doc keys, so both sources form one tree.
type refNode struct {
	name     string
	path     string // full dotted path, e.g. "cloud.aws.s3"
	value    any    // surface value when hasValue is true
	hasValue bool
	isMap    bool // surface value is a map[string]any (a sub-namespace container)
	children map[string]*refNode
}

func (n *refNode) child(seg, path string) *refNode {
	if n.children == nil {
		n.children = make(map[string]*refNode)
	}
	c := n.children[seg]
	if c == nil {
		c = &refNode{name: seg, path: path}
		n.children[seg] = c
	}
	return c
}

// buildNamespaceTree merges the walked surface (recursing into nested maps) with
// any documented doc-map keys under the namespace prefix into a single tree, so
// statically-reachable members and runtime-handle members (documented only via
// orphan doc keys) are numbered and levelled by their real dotted-path depth.
func buildNamespaceTree(nsName string, members map[string]any, docs map[string]MemberDoc) *refNode {
	root := &refNode{name: nsName, path: nsName}
	for k, v := range members {
		insertSurfaceMember(root, k, nsName+"."+k, v)
	}
	prefix := nsName + "."
	for key := range docs {
		if !strings.HasPrefix(key, prefix) {
			continue
		}
		cur, p := root, nsName
		for _, seg := range strings.Split(key[len(prefix):], ".") {
			p += "." + seg
			cur = cur.child(seg, p)
		}
	}
	return root
}

// insertSurfaceMember adds a walked member to the tree, descending into nested
// namespace maps so each level becomes its own node.
func insertSurfaceMember(parent *refNode, name, path string, v any) {
	n := parent.child(name, path)
	n.hasValue = true
	if nested, ok := v.(map[string]any); ok {
		n.isMap = true
		for k, cv := range nested {
			insertSurfaceMember(n, k, path+"."+k, cv)
		}
		return
	}
	n.value = v
}

// emitNamespaceTree renders a namespace's members as a hierarchical tree: each
// child is numbered <parentNum>.<index> (1-based, in sorted dotted-path order)
// and rendered at heading level 3+depth — capped at markdown's H6 — so the
// dotted-path hierarchy shows up in both the section numbers and the heading
// levels (and therefore the TOC). Direct members start at H4.
func emitNamespaceTree(w *errWriter, members map[string]any, nsName string, docs map[string]MemberDoc, nsNum string) {
	root := buildNamespaceTree(nsName, members, docs)
	emitRefChildren(w, root, docs, nsNum, 4)
}

func emitRefChildren(w *errWriter, parent *refNode, docs map[string]MemberDoc, parentNum string, level int) {
	keys := make([]string, 0, len(parent.children))
	for k := range parent.children {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	lvl := level
	if lvl > 6 {
		lvl = 6
	}
	for i, k := range keys {
		n := parent.children[k]
		num := parentNum // "" stays "" for unnumbered output (still nests by level)
		if parentNum != "" {
			num = parentNum + "." + strconv.Itoa(i+1)
		}
		emitRefNode(w, n, docs, num, lvl)
		emitRefChildren(w, n, docs, num, level+1)
	}
}

// emitRefNode renders one tree node: a callable/method gets a fenced signature
// plus its documented body; a container (a sub-namespace surface map, or a
// documented-but-not-callable service group) gets a heading and its summary
// only. num is "" for unnumbered output; level is the heading depth in '#'s.
func emitRefNode(w *errWriter, n *refNode, docs map[string]MemberDoc, num string, level int) {
	doc := docs[n.path]
	var signature string
	hasSig := false
	switch {
	case n.hasValue && !n.isMap:
		// A surface leaf (callable or value): reflected or documented signature.
		signature = sigForMember(n.name, n.value, doc)
		hasSig = true
	case !n.hasValue && (len(doc.Params) > 0 || doc.ReturnType != ""):
		// A documented runtime-handle method (no surface value): build the
		// signature from the doc.
		ret := doc.ReturnType
		if ret == "" {
			ret = "void"
		}
		signature = n.name + sigFromParams(doc.Params, ret)
		hasSig = true
	}
	writeReferenceEntry(w, level, num, n.path, doc, signature, hasSig)
}

// writeReferenceEntry emits a single `<level '#'s> <num> <path>` section: an
// optional fenced signature (when hasSig), then the documented body. num is ""
// for unnumbered output.
func writeReferenceEntry(w *errWriter, level int, num, path string, doc MemberDoc, signature string, hasSig bool) {
	w.WriteString("\n" + strings.Repeat("#", level) + " " + numberedHeading(num, path) + "\n")
	if hasSig {
		w.WriteString("\n```\n" + signature + "\n```\n")
	}
	writeDocBody(w, doc)
}

// writeDocBody writes the Summary paragraph, Parameters list, Returns, Throws,
// and Example fenced block for a member, omitting every empty section.
func writeDocBody(w *errWriter, doc MemberDoc) {
	if s := strings.TrimSpace(doc.Summary); s != "" {
		w.WriteString("\n" + s + "\n")
	}

	if len(doc.Params) > 0 {
		w.WriteString("\n**Parameters**\n\n")
		for _, p := range doc.Params {
			typ := p.Type
			if typ == "" {
				typ = "unknown"
			}
			if p.Optional {
				typ += ", optional"
			}
			line := "- `" + p.Name + "` *(" + typ + ")*"
			if d := strings.TrimSpace(p.Desc); d != "" {
				line += " — " + d
			}
			w.WriteString(line + "\n")
		}
	}

	if r := strings.TrimSpace(doc.Returns); r != "" {
		w.WriteString("\n**Returns:** " + r + "\n")
	}
	if errs := strings.TrimSpace(doc.Errors); errs != "" {
		w.WriteString("\n**Throws:** " + errs + "\n")
	}
	if ex := strings.TrimSpace(doc.Example); ex != "" {
		w.WriteString("\n```ts\n" + ex + "\n```\n")
	}
}

// topLevelSig builds the signature line for a top-level registration. When the
// MemberDoc has Params it uses sigFromParams; otherwise it falls back to a
// reflected/`(...)` form consistent with the d.ts emitter.
func topLevelSig(reg registration, doc MemberDoc) string {
	if reg.kind == regNamespace {
		return reg.name
	}
	value := reg.value
	if m, ok := value.(factoryMarker); ok {
		value = introspectValueFactory(m)
	}
	return sigForMember(reg.name, value, doc)
}

func introspectValueFactory(m factoryMarker) (value any) {
	defer func() {
		if r := recover(); r != nil {
			value = nil
		}
	}()
	return m.fn(nil, nil)
}

// sigForMember produces the fenced signature text for a member. With Params it
// reuses sigFromParams (Param types, no deep type recursion). Without Params it
// reflects a simple `name(...)` form, keeping it consistent and shallow.
func sigForMember(name string, v any, doc MemberDoc) string {
	if a, ok := v.(AsyncBinding); ok {
		ret := asyncReturnType(doc, a)
		if len(doc.Params) > 0 {
			return name + sigFromParams(doc.Params, ret)
		}
		return name + "(...args: unknown[]): " + ret
	}
	t := reflect.TypeOf(v)
	isFunc := t != nil && t.Kind() == reflect.Func
	if isFunc {
		// Callable member: a documented signature (Params and/or ReturnType)
		// or the reflected `(...args)` fallback.
		if len(doc.Params) > 0 || doc.ReturnType != "" {
			ret := doc.ReturnType
			if ret == "" {
				ret = "void"
			}
			return name + sigFromParams(doc.Params, ret)
		}
		return name + "(...args: unknown[])"
	}
	// Non-callable value (e.g. runtime.argv): render as a property, matching
	// the d.ts (`argv: string[]`), not a call.
	if doc.ReturnType != "" {
		return name + ": " + doc.ReturnType
	}
	return name
}
