// AUTO-GENERATED by scriptengine.Engine.WriteTypes — do not edit by hand.

/** sercon's built-in script surface. The full reference lives in MANUAL.md; the JSDoc blocks here are the at-a-glance summary. */
declare const api: {
  archive: {
    /** Create a zip / tar / tar.gz at destPath from a list of paths. Format inferred from extension. */
    create(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Extract a zip / tar / tar.gz to destDir. opts.overwrite controls O_EXCL behaviour. */
    extract(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  assert: {
    /** Throw when actual != expected (strict equality on primitives, deep equality on objects). Optional msg appears in the error. */
    equal(arg0: unknown, arg1: unknown, arg2: unknown[]): void;
    /** Throw when cond is falsy. Optional msg appears in the error. */
    ok(arg0: unknown, arg1: unknown[]): void;
  };
  barcode: {
    /** Available decode formats (qr / datamatrix / aztec / code128 / code39 / code93 / codabar / ean13 / ean8 / upca / upce / itf). PDF417 is encode-only. */
    decodableFormats(): string[];
    /** Decode a PNG/JPEG/WebP image to { format, text } via gozxing. Optional format hint skips the auto-detect walk. EAN/UPC need a quiet zone in the input. */
    decode(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Render data into a PNG of the chosen format. opts.width / opts.height default to 256x256 (2D) or 400x120 (1D). opts.quietZone (true or px count) pads a white margin — required for EAN/UPC to decode. */
    encode(...args: unknown[]): Promise<Uint8Array>;
    /** Available encode formats (qr / datamatrix / aztec / pdf417 / code128 / code39 / codabar / ean13 / ean8 / upca). */
    formats(): string[];
  };
  checkdigit: {
    /** Supported algorithms (luhn / isbn10 / isbn13 / ean13 / ean8 / upca). */
    algos(): string[];
    /** Compute the missing trailing check digit for a partial input. */
    compute(arg0: string, arg1: string): string;
    /** Diagnostic combining validate + compute: { valid, given, computed, … }. */
    inspect(arg0: string, arg1: string): Record<string, unknown>;
    /** Return whether the input passes the named algorithm's check digit. */
    validate(arg0: string, arg1: string): boolean;
  };
  compression: {
    /** Available compression algorithm names (gzip / deflate / zlib / bzip2 / zstd / brotli / lz4 / xz / snappy). */
    algos(): string[];
    /** Compress data with the named algorithm. Returns Uint8Array. */
    compress(...args: unknown[]): Promise<Uint8Array>;
    /** Decompress data previously produced by compress (same algorithm name required). */
    decompress(...args: unknown[]): Promise<Uint8Array>;
  };
  diff: {
    /** Unified-diff two text inputs. opts: context (default 3), fromFile / toFile (default 'a' / 'b'). Binary inputs return { binary: true } with an empty diff. */
    compare(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  email: {
    /** Run all five email probes in parallel — five-way handshake aggregate. */
    all(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe BIMI: TXT(<selector>._bimi.<domain>); selector defaults to 'default'. */
    bimi(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Query TXT(_dmarc.<domain>) and parse policy / pct / rua / ruf tags. */
    dmarc(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe MTA-STS: TXT(_mta-sts.<domain>) plus the fetched policy file. */
    mtaSts(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Query TXT(<domain>) for SPF, return record + parsed mechanisms + all-policy. */
    spf(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe TLS-RPT: TXT(_smtp._tls.<domain>) and parse rua. */
    tlsRpt(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  encrypt: {
    /** Open an age payload (binary or armored, auto-detected) with one of the supplied identities (AGE-SECRET-KEY-1... private keys). Cross-check catches public-as-identity mistakes; wrong identity throws age's 'did not match' error. */
    decrypt(arg0: unknown, arg1: unknown): unknown;
    /** Classify a recipient / identity string. Returns { backend: 'age'|'pgp'|'unknown', kind?: 'public'|'private' }. Pure prefix matching; no parsing or I/O. PGP encrypt/decrypt is a future cut — classifier is useful standalone. */
    detectBackend(arg0: string): unknown;
    /** Seal data to one or more recipients (age1... public keys). Default output is binary; opts.armored=true wraps in age's ASCII armor for JSON/YAML/email embedding. Multi-recipient encryption lets any listed identity decrypt. */
    encrypt(arg0: unknown, arg1: unknown, arg2: unknown): unknown;
    /** Generate a fresh X25519 keypair. Returns { publicKey: 'age1...', privateKey: 'AGE-SECRET-KEY-1...' }. */
    keygen(): unknown;
    /** Re-encrypt for a new recipient set without exposing plaintext to JS. Output format defaults to match the input; opts.armored forces. Internal decrypt+encrypt loop. */
    rekey(arg0: unknown, arg1: unknown, arg2: unknown, arg3: unknown): unknown;
  };
  env: {
    /** Read an environment variable. Returns undefined when unset (not empty string). */
    get(...args: unknown[]): unknown;
  };
  exec: {
    /** HTTP via recon (preferred) or curl (fallback). 4xx / 5xx resolve as status; transport errors and timeouts throw. opts.backend = 'auto' | 'recon' | 'curl'. */
    http(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Run a subprocess. String cmd → /bin/sh -c (or `cmd /C` on Windows); array cmd → argv. Non-zero exits resolve; spawn failures and timeouts throw. */
    shell(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  gh: {
    /** Probe gh's auth state. Missing gh / unauthenticated resolve with { authenticated: false, … } — only context cancellation throws. */
    authStatus(...args: unknown[]): Promise<Record<string, unknown>>;
    /** List pull requests on the cwd's repo (or opts.cwd). Defaults: open state, limit 30. Filters: state / limit / author. */
    prList(...args: unknown[]): Promise<Record<string, unknown>[]>;
    /** Repo metadata. With no arg uses cwd's repo; pass 'owner/name' for any repo gh can see. owner + defaultBranch are pre-flattened. */
    repoView(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  git: {
    /** Stage one path (string) or several (string[]). */
    add(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Current branch (empty when HEAD is detached) plus the list of local branches. */
    branch(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Create a commit; returns the post-commit HEAD SHA. opts.allowEmpty toggles --allow-empty. */
    commit(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Aggregate { files, insertions, deletions } from `git diff --shortstat`. Default revRange HEAD~1..HEAD. */
    diffStat(...args: unknown[]): Promise<Record<string, unknown>>;
    /** True iff `git status --porcelain` is empty. */
    isClean(...args: unknown[]): Promise<boolean>;
    /** Recent commits as { sha, shortSha, author, email, timestamp, subject }. opts.limit / opts.revRange. */
    log(...args: unknown[]): Promise<Record<string, unknown>[]>;
    /** Full 40-char SHA for the given rev. Invalid refs throw. */
    revParse(...args: unknown[]): Promise<string>;
    /** Escape hatch: run any `git <args>`, get { stdout, stderr, exitCode } — exitCode is data, not a throw. */
    runText(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Parsed `git status --porcelain` entries: { path, indexStatus, workingStatus }. */
    status(...args: unknown[]): Promise<Record<string, unknown>[]>;
  };
  hash: {
    /** BLAKE3 hex digest (32-byte output, lukechampine.com/blake3). */
    blake3(...args: unknown[]): unknown;
    /** CRC-32 (IEEE polynomial), zero-padded to 8 hex chars. */
    crc32(...args: unknown[]): unknown;
    /** MD5 hex digest of a UTF-8 input. Avoid for security purposes — exposed for compatibility with legacy fingerprints. */
    md5(...args: unknown[]): unknown;
    /** SHA-1 hex digest of a UTF-8 input. Avoid for security purposes. */
    sha1(...args: unknown[]): unknown;
    /** SHA-256 hex digest of a UTF-8 input. */
    sha256(...args: unknown[]): unknown;
    /** SHA-384 hex digest of a UTF-8 input. */
    sha384(...args: unknown[]): unknown;
    /** SHA-3 256-bit hex digest. The underscore in the name matches recon's binding. */
    sha3_256(...args: unknown[]): unknown;
    /** SHA-3 512-bit hex digest. */
    sha3_512(...args: unknown[]): unknown;
    /** SHA-512 hex digest of a UTF-8 input. */
    sha512(...args: unknown[]): unknown;
  };
  http: {
    /** Perform an HTTP GET with a 5-second default timeout. Returns { status, body }. */
    get(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Perform an HTTP POST with a 5-second default timeout. Returns { status, body }. */
    post(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  jq: {
    /** Run a jq filter over data and return the first emitted value (or null). */
    query(...args: unknown[]): Promise<unknown>;
    /** Run a jq filter and drain the iterator into an array. */
    queryAll(...args: unknown[]): Promise<unknown[]>;
  };
  jwt: {
    /** Sign a claims object. secret is raw bytes for HS*; PEM-encoded private key for RS*/PS*/ES*/EdDSA. opts.algorithm defaults to HS256. Cross-check (PEM + HMAC, or bytes + asymmetric) throws. */
    sign(arg0: Record<string, unknown>, arg1: string, arg2: unknown): unknown;
    /** Verify signature + standard claims (exp/nbf/iat) + optional aud/iss. Set opts.algorithm for the algo-confusion guard. Resolves { valid:true, claims } or { valid:false, reason }; only structural input errors throw. */
    validate(arg0: string, arg1: string, arg2: unknown): unknown;
    /** Decode header + payload WITHOUT verifying the signature. Useful for inspection / debugging auth flows. Malformed input throws. */
    view(arg0: string): unknown;
  };
  /** Stringify each argument and print one space-separated line to stdout. The script-side equivalent of console.log without buffering. */
  log(...args: unknown[]): unknown;
  net: {
    /** Look up A / AAAA / MX / TXT / CNAME / NS records. Default: all five. */
    dns(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Query an NTPv4 server (UDP 123) and report offset, RTT, stratum, root delay / dispersion. */
    ntp(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Dial a TCP target and report latency + resolved IP. Default timeout 5s. */
    tcp(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Open a TLS connection (InsecureSkipVerify; for probing only) and return the cert chain summary. */
    tls(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Two-hop WHOIS via the IANA referral, returning the parsed record plus the raw response text. */
    whois(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  path: {
    /** Final segment of a path; optional suffix is stripped if it matches. */
    basename(...args: unknown[]): unknown;
    /** Directory portion of a path. POSIX-style; trailing slashes are stripped. */
    dirname(...args: unknown[]): unknown;
  };
  preg: {
    /** First hit of /pattern/flags against subject, or null. Returns { match, groups, index }; optional groups that didn't match surface as empty strings. */
    match(arg0: string, arg1: string): unknown;
    /** Every hit of /pattern/flags against subject, as an array of { match, groups, index } objects. */
    matchAll(arg0: string, arg1: string): unknown;
    /** Substitute every match of /pattern/flags in subject. Replacement uses Go's $1 / ${1} backref syntax — PHP's \1 form is NOT translated. */
    replace(arg0: string, arg1: string, arg2: string): unknown;
  };
  preg2: {
    /** First hit of /pattern/flags via regexp2 (PCRE). Supports lookahead/lookbehind/backreferences. Same { match, groups, index } shape as preg. No linear-time guarantee. */
    match(arg0: string, arg1: string): unknown;
    /** Every hit of /pattern/flags via regexp2 (PCRE), as an array of { match, groups, index }. */
    matchAll(arg0: string, arg1: string): unknown;
    /** Substitute every match of /pattern/flags via regexp2. Replacement uses .NET $1 / ${1} syntax. Backtracking engine — keep a timeout around untrusted input. */
    replace(arg0: string, arg1: string, arg2: string): unknown;
  };
  sqlite: {
    /** Open a SQLite database (':memory:' or a file path; created if absent). Resolves to a handle { exec, query, queryValue, close }. Connection is Ping-ed before resolving. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  str: {
    /** Standard base64; URL-safe input is accepted via auto-detect. */
    base64Decode(...args: unknown[]): unknown;
    /** Standard base64 (with padding). */
    base64Encode(...args: unknown[]): unknown;
    /** Inverse of nl2br: <br>, <br/>, <br /> → '\n'. */
    br2nl(...args: unknown[]): unknown;
    /** Decode named and numeric HTML entities to their UTF-8 equivalents. */
    htmlEntityDecode(...args: unknown[]): unknown;
    /** Shortcut for pad(side: 'left'). */
    lpad(...args: unknown[]): unknown;
    /** Like trim, left side only. */
    ltrim(...args: unknown[]): unknown;
    /** Replace newlines with <br> (or <br/> when xhtml=true). */
    nl2br(...args: unknown[]): unknown;
    /** Canonicalise any mix of \r\n, \r, \n to the requested style ('lf' | 'crlf' | 'cr'). */
    normalizeNewlines(...args: unknown[]): unknown;
    /** Pad to `len` with `padChar` (default ' '). `side` is 'right' (default), 'left', or 'both'. */
    pad(...args: unknown[]): unknown;
    /** sprintf + write to stdout. */
    printf(...args: unknown[]): unknown;
    /** Rune-aware reversal — `reverse('café')` is `'éfac'`. */
    reverse(...args: unknown[]): unknown;
    /** Shortcut for pad(side: 'right'). */
    rpad(...args: unknown[]): unknown;
    /** Like trim, right side only. */
    rtrim(...args: unknown[]): unknown;
    /** Go's fmt verbs (%s, %d, %x, %.2f, %v, %t, %q, …) — not PHP's. */
    sprintf(...args: unknown[]): unknown;
    /** Remove HTML tags and decode common entities. */
    stripHtml(...args: unknown[]): unknown;
    /** Strip whitespace (or any char in the optional mask string) from both ends. */
    trim(...args: unknown[]): unknown;
    /** Inverse of urlEncode. */
    urlDecode(...args: unknown[]): unknown;
    /** Form-encoding ('+' for space). For path segments use encodeURIComponent (provided by goja). */
    urlEncode(...args: unknown[]): unknown;
  };
  text: {
    /** Decode bytes in a named charset to a UTF-8 string. */
    decode(...args: unknown[]): Promise<string>;
    /** Detect the most-likely charset of a byte sequence (saintfish/chardet). Returns top guess + candidates. */
    detect(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Encode a UTF-8 string to bytes in the named charset. */
    encode(...args: unknown[]): Promise<Uint8Array>;
  };
  time: {
    /** Format a unix-ms timestamp through strftime tokens. Optional IANA tz (e.g. 'Europe/Stockholm'); default is the host's local zone. */
    format(...args: unknown[]): unknown;
    /** Wall-clock milliseconds since the Unix epoch. */
    nowMs(): number;
    /** Resolve after `ms` milliseconds. Cancellable via the engine timeout. */
    sleep(...args: unknown[]): Promise<unknown>;
  };
};

