// AUTO-GENERATED by scriptengine.Engine.WriteTypes — do not edit by hand.

declare const api: {
  assert: {
    equal(arg0: unknown, arg1: unknown, arg2: unknown[]): void;
    ok(arg0: unknown, arg1: unknown[]): void;
  };
  email: {
    dmarc(...args: unknown[]): Promise<Record<string, unknown>>;
    spf(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  env: {
    get(...args: unknown[]): unknown;
  };
  hash: {
    blake3(...args: unknown[]): unknown;
    crc32(...args: unknown[]): unknown;
    md5(...args: unknown[]): unknown;
    sha1(...args: unknown[]): unknown;
    sha256(...args: unknown[]): unknown;
    sha384(...args: unknown[]): unknown;
    sha3_256(...args: unknown[]): unknown;
    sha3_512(...args: unknown[]): unknown;
    sha512(...args: unknown[]): unknown;
  };
  http: {
    get(...args: unknown[]): Promise<Record<string, unknown>>;
    post(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  log(...args: unknown[]): unknown;
  net: {
    dns(...args: unknown[]): Promise<Record<string, unknown>>;
    ntp(...args: unknown[]): Promise<Record<string, unknown>>;
    tcp(...args: unknown[]): Promise<Record<string, unknown>>;
    tls(...args: unknown[]): Promise<Record<string, unknown>>;
    whois(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  path: {
    basename(...args: unknown[]): unknown;
    dirname(...args: unknown[]): unknown;
  };
  str: {
    base64Decode(...args: unknown[]): unknown;
    base64Encode(...args: unknown[]): unknown;
    br2nl(...args: unknown[]): unknown;
    htmlEntityDecode(...args: unknown[]): unknown;
    lpad(...args: unknown[]): unknown;
    ltrim(...args: unknown[]): unknown;
    nl2br(...args: unknown[]): unknown;
    normalizeNewlines(...args: unknown[]): unknown;
    pad(...args: unknown[]): unknown;
    printf(...args: unknown[]): unknown;
    reverse(...args: unknown[]): unknown;
    rpad(...args: unknown[]): unknown;
    rtrim(...args: unknown[]): unknown;
    sprintf(...args: unknown[]): unknown;
    stripHtml(...args: unknown[]): unknown;
    trim(...args: unknown[]): unknown;
    urlDecode(...args: unknown[]): unknown;
    urlEncode(...args: unknown[]): unknown;
  };
  time: {
    format(...args: unknown[]): unknown;
    nowMs(): number;
    sleep(...args: unknown[]): Promise<unknown>;
  };
};

