// AUTO-GENERATED by scriptengine.Engine.WriteTypes — do not edit by hand.
// Reserved globals: codec, console, crypto, db, fs, net, runtime, server, services, text, tui.

/** Browser/Node-style console shim: log/info/debug to stdout, warn/error to stderr. For porting scripts; runtime.log is the native equivalent. */
declare const console: {
  /**
   * Alias of console.log — stringified arguments, space-joined, to stdout.
   * @param args Values to print; identical formatting and stdout destination as console.log.
   * @returns void — output is written to stdout as a side effect.
   */
  debug(args: ...unknown[]): void;
  /**
   * Like console.log but writes to stderr.
   * @param args Values to print; same space-joined / JSON formatting as console.log but routed to stderr.
   * @returns void — output is written to stderr as a side effect.
   */
  error(args: ...unknown[]): void;
  /**
   * Alias of console.log — stringified arguments, space-joined, to stdout.
   * @param args Values to print; identical formatting and stdout destination as console.log.
   * @returns void — output is written to stdout as a side effect.
   */
  info(args: ...unknown[]): void;
  /**
   * Print a space-joined line of the arguments to stdout. Primitives print raw; objects/arrays render as JSON. Browser/Node-compatible; same output as runtime.log.
   * @param args Values to print, joined by single spaces and terminated with a newline. Primitives (string/number/boolean/null/undefined) print raw; objects and arrays render as JSON via JSON.stringify, falling back to String() for functions and circular references.
   * @returns void — output is written to stdout as a side effect.
   */
  log(args: ...unknown[]): void;
  /**
   * Like console.log but writes to stderr.
   * @param args Values to print; same space-joined / JSON formatting as console.log but routed to stderr.
   * @returns void — output is written to stderr as a side effect.
   */
  warn(args: ...unknown[]): void;
};

/** Script-host scaffolding: logging, assertions, time, environment, runtime.argv. */
declare const runtime: {
  /**
   * Per-script argument vector: [programName, scriptPath, ...userArgs]. argv[0] is the program name (sercon), argv[1] is the running script path, and any args after `--` on the command line start at argv[2].
   * @returns string[] — the per-run argument vector. argv[0] is the program name ("sercon"), argv[1] is the running script's path, and entries from index 2 onward are the user arguments passed after `--` on the command line. This is a value (property), not a function.
   */
  argv: string[];
  assert: {
    /**
     * Throw when actual != expected (strict equality on primitives, deep equality on objects). Optional msg appears in the error.
     * @param actual The value produced by the code under test.
     * @param expected The value to compare against. Primitives use strict equality; objects/arrays use deep structural equality (key order ignored).
     * @param msg Optional message prefixed onto the thrown error; defaults to "assert.equal failed".
     * @returns void — returns nothing when the values match.
     */
    equal(actual: unknown, expected: unknown, msg?: string): void;
    /**
     * Throw when cond is falsy. Optional msg appears in the error.
     * @param cond A value tested for truthiness (JS coercion: 0, "", null, undefined, NaN and false are falsy).
     * @param msg Optional message used as the thrown error text; defaults to "assert.ok failed".
     * @returns void — returns nothing when cond is truthy.
     */
    ok(cond: unknown, msg?: string): void;
  };
  env: {
    /**
     * Read an environment variable. Returns undefined when unset (not empty string).
     * @param name Environment variable name to look up.
     * @returns string — the variable's value, or undefined when the variable is not set. A variable set to the empty string returns "", which is distinct from undefined.
     */
    get(name: string): string | undefined;
  };
  /**
   * Print one space-separated line of the arguments to stdout. Primitives print raw; objects/arrays render as JSON (circular refs fall back to [object Object]). The script-side equivalent of console.log.
   * @param args Zero or more values to print. They are joined with single spaces; primitives stringify directly, objects/arrays are JSON-encoded.
   * @returns void — writes a single newline-terminated line to stdout.
   */
  log(args: unknown[]): void;
  time: {
    /**
     * Format a unix-ms timestamp through strftime tokens. Optional IANA tz (e.g. 'Europe/Stockholm'); default is the host's local zone.
     * @param ms Milliseconds since the Unix epoch (e.g. from time.nowMs). Coerced to an integer.
     * @param layout strftime-style layout. Supported tokens: %Y %y %m %d %H %M %S %T %F %j %A %a %B %b %z %Z and %% (literal percent). Unknown %X tokens pass through verbatim.
     * @param tz IANA timezone name (e.g. "Europe/Stockholm", "UTC"). Defaults to the host's local zone when omitted/null/undefined.
     * @returns string — the timestamp rendered in tz with the given layout.
     */
    format(ms: number, layout: string, tz?: string): string;
    /**
     * Wall-clock milliseconds since the Unix epoch.
     * @returns number — integer milliseconds since 1970-01-01T00:00:00Z (host wall clock).
     */
    nowMs(): number;
    /**
     * Resolve after `ms` milliseconds. Cancellable via the engine timeout.
     * @param ms Delay in milliseconds. Coerced to an integer; non-positive values resolve effectively immediately.
     * @returns Promise<void> — resolves once the delay elapses.
     */
    sleep(ms: number): Promise<unknown>;
  };
};

/** Hashing, JWT, age encryption — anything that produces a digest, signature, or ciphertext. */
declare const crypto: {
  encrypt: {
    /**
     * Open a payload with one of the supplied identities. Routes to age or PGP based on the identity / ciphertext format. age: binary or armored auto-detected. Wrong identity throws.
     * @param ciphertext The encrypted payload; age armor and PGP armor are auto-detected.
     * @param identities One or more private keys. AGE-SECRET-KEY-1... identities use the age backend; -----BEGIN PGP PRIVATE KEY BLOCK----- entries (or an armored PGP message) use the PGP backend.
     * @returns Uint8Array — the decrypted plaintext bytes (decode with new TextDecoder().decode(...) for a string).
     */
    decrypt(ciphertext: string | Uint8Array | ArrayBuffer, identities: string | string[]): Uint8Array;
    /**
     * Classify a recipient / identity string. Returns { backend: 'age'|'pgp'|'unknown', kind?: 'public'|'private' }. Pure prefix matching; no parsing or I/O.
     * @param input A recipient or identity string to classify (age bech32, age SSH public key, or PGP armored block).
     * @returns { backend: "age" | "pgp" | "unknown", kind?: "public" | "private" } — kind is present only when the backend was identified.
     */
    detectBackend(input: string): { backend: string; kind?: string };
    /**
     * Seal data to recipients. age public keys (age1...) → age backend (opts.armored for ASCII); PGP public-key blocks → PGP backend (always armored). Auto-dispatched on key format. Multi-recipient: any listed identity decrypts.
     * @param data Plaintext to encrypt.
     * @param recipients One or more recipient public keys. age1... bech32 keys use the age backend; -----BEGIN PGP PUBLIC KEY BLOCK----- entries use the PGP backend. Backends cannot be mixed in one call.
     * @param opts armored (age backend only) wraps the output in age ASCII armor; defaults to false (binary). Ignored on the PGP path, which is always armored.
     * @returns Uint8Array — the ciphertext (binary age, ASCII-armored age when opts.armored, or armored PGP message bytes).
     */
    encrypt(data: string | Uint8Array | ArrayBuffer, recipients: string | string[], opts?: { armored?: boolean }): Uint8Array;
    /**
     * Generate a fresh age X25519 keypair. Returns { publicKey: 'age1...', privateKey: 'AGE-SECRET-KEY-1...' }.
     * @returns { publicKey: string, privateKey: string } — publicKey is the shareable age1... recipient; privateKey is the secret AGE-SECRET-KEY-1... identity.
     */
    keygen(): { publicKey: string; privateKey: string };
    /**
     * Generate a PGP keypair (RSA 2048). opts.name / opts.email populate the user ID. Returns armored { publicKey, privateKey } blocks. encrypt/decrypt auto-route to PGP when they see these.
     * @param opts name and email populate the primary user ID; both default to empty (fine for throwaway keys).
     * @returns { publicKey: string, privateKey: string } — both ASCII-armored PGP key blocks (-----BEGIN PGP PUBLIC/PRIVATE KEY BLOCK-----).
     */
    keygenPgp(opts?: { name?: string, email?: string }): { publicKey: string; privateKey: string };
    /**
     * Re-encrypt for a new recipient set without exposing plaintext to JS. Output format defaults to match the input; opts.armored forces. Internal decrypt+encrypt loop.
     * @param ciphertext The existing age ciphertext to re-key (armor auto-detected).
     * @param oldIdentities Current AGE-SECRET-KEY-1... private keys used to decrypt the existing ciphertext.
     * @param newRecipients New age1... public keys to encrypt the result for.
     * @param opts armored forces the output armor state; default preserves the input's armor state.
     * @returns Uint8Array — the re-encrypted ciphertext for the new recipient set.
     */
    rekey(ciphertext: string | Uint8Array | ArrayBuffer, oldIdentities: string | string[], newRecipients: string | string[], opts?: { armored?: boolean }): Uint8Array;
  };
  hash: {
    /**
     * BLAKE3 hex digest (32-byte output, lukechampine.com/blake3).
     * @param input Data to hash, interpreted as a UTF-8 byte sequence.
     * @returns string — 64-char lowercase hex digest (256-bit output).
     */
    blake3(input: string): string;
    /**
     * CRC-32 (IEEE polynomial), zero-padded to 8 hex chars.
     * @param input Data to checksum, interpreted as a UTF-8 byte sequence.
     * @returns string — 8-char zero-padded lowercase hex checksum.
     */
    crc32(input: string): string;
    /**
     * MD5 hex digest of a UTF-8 input. Avoid for security purposes — exposed for compatibility with legacy fingerprints.
     * @param input Data to hash, interpreted as a UTF-8 byte sequence.
     * @returns string — 32-char lowercase hex digest.
     */
    md5(input: string): string;
    /**
     * SHA-1 hex digest of a UTF-8 input. Avoid for security purposes.
     * @param input Data to hash, interpreted as a UTF-8 byte sequence.
     * @returns string — 40-char lowercase hex digest.
     */
    sha1(input: string): string;
    /**
     * SHA-256 hex digest of a UTF-8 input.
     * @param input Data to hash, interpreted as a UTF-8 byte sequence.
     * @returns string — 64-char lowercase hex digest.
     */
    sha256(input: string): string;
    /**
     * SHA-384 hex digest of a UTF-8 input.
     * @param input Data to hash, interpreted as a UTF-8 byte sequence.
     * @returns string — 96-char lowercase hex digest.
     */
    sha384(input: string): string;
    /**
     * SHA-3 256-bit hex digest. The underscore in the name matches recon's binding.
     * @param input Data to hash, interpreted as a UTF-8 byte sequence.
     * @returns string — 64-char lowercase hex digest.
     */
    sha3_256(input: string): string;
    /**
     * SHA-3 512-bit hex digest.
     * @param input Data to hash, interpreted as a UTF-8 byte sequence.
     * @returns string — 128-char lowercase hex digest.
     */
    sha3_512(input: string): string;
    /**
     * SHA-512 hex digest of a UTF-8 input.
     * @param input Data to hash, interpreted as a UTF-8 byte sequence.
     * @returns string — 128-char lowercase hex digest.
     */
    sha512(input: string): string;
  };
  jwt: {
    /**
     * Sign a claims object. secret is raw bytes for HS*; PEM-encoded private key for RS*/PS*/ES*/EdDSA; or a JWK JSON object (kty picks the key type) for any algorithm. opts.algorithm defaults to HS256.
     * @param claims Claims payload. Passed through to MapClaims; RFC 7519 reserved claims (exp/nbf/iat/iss/aud/sub) are honoured. Reserved claims are NOT synthesised — set iat/exp explicitly if you want them.
     * @param secret Key material: raw HMAC bytes for HS256/384/512, a PEM-encoded private key (-----BEGIN ...) for RS*/PS*/ES*/EdDSA, or a JWK JSON object ({"kty":...}).
     * @param opts algorithm names the RFC 7518 alg (HS256/HS384/HS512, RS256/384/512, PS256/384/512, ES256/384/512, EdDSA); case-insensitive. Defaults to HS256.
     * @returns string — the signed compact-serialisation JWT (header.payload.signature).
     */
    sign(claims: Record<string, unknown>, secret: string, opts?: { algorithm?: string }): string;
    /**
     * Verify signature + standard claims (exp/nbf/iat) + optional aud/iss. secret accepts raw bytes / PEM public key / JWK. Set opts.algorithm for the algo-confusion guard. Resolves { valid:true, claims } or { valid:false, reason }.
     * @param token The compact-serialisation JWT to verify.
     * @param secret Verification key: raw HMAC bytes, a PEM-encoded public key (or certificate), or a JWK JSON object.
     * @param opts algorithm pins the accepted alg (algorithm-confusion guard); when unset, any supported alg is accepted. audience / issuer enforce the aud / iss claims when set.
     * @returns { valid: true, claims: object } on success, or { valid: false, reason: string } on any verification / claim failure.
     */
    validate(token: string, secret: string, opts?: { algorithm?: string, audience?: string, issuer?: string }): { valid: boolean; claims?: object; reason?: string };
    /**
     * Decode header + payload WITHOUT verifying the signature. Useful for inspection / debugging auth flows. Malformed input throws.
     * @param token A compact-serialisation JWT (three dot-separated base64url segments).
     * @returns { header: object, payload: object, signature: string } — decoded header and payload (object key order preserved) plus the raw signature segment.
     */
    view(token: string): { header: object; payload: object; signature: string };
  };
};

/** String / regex / charset / data manipulation — all text-shaped transforms. */
declare const text: {
  charset: {
    /** Decode bytes in a named charset to a UTF-8 string. */
    decode(...args: unknown[]): Promise<string>;
    /** Detect the most-likely charset of a byte sequence (saintfish/chardet). Returns top guess + candidates. */
    detect(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Encode a UTF-8 string to bytes in the named charset. */
    encode(...args: unknown[]): Promise<Uint8Array>;
  };
  diff: {
    /** Unified-diff two text inputs. opts: context (default 3), fromFile / toFile (default 'a' / 'b'). Binary inputs return { binary: true } with an empty diff. */
    compare(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  jq: {
    /** Run a jq filter over data and return the first emitted value (or null). */
    query(...args: unknown[]): Promise<unknown>;
    /** Run a jq filter and drain the iterator into an array. */
    queryAll(...args: unknown[]): Promise<unknown[]>;
  };
  preg: {
    /** First hit of /pattern/flags against subject, or null. Returns { match, groups, index }; optional groups that didn't match surface as empty strings. */
    match(arg0: string, arg1: string): unknown;
    /** Every hit of /pattern/flags against subject, as an array of { match, groups, index } objects. */
    matchAll(arg0: string, arg1: string): unknown;
    /** Substitute every match of /pattern/flags in subject. Replacement uses Go's $1 / ${1} backref syntax — PHP's \1 form is NOT translated. */
    replace(arg0: string, arg1: string, arg2: string): unknown;
  };
  preg2: {
    /** First hit of /pattern/flags via regexp2 (PCRE). Supports lookahead/lookbehind/backreferences. Same { match, groups, index } shape as preg. No linear-time guarantee. */
    match(arg0: string, arg1: string): unknown;
    /** Every hit of /pattern/flags via regexp2 (PCRE), as an array of { match, groups, index }. */
    matchAll(arg0: string, arg1: string): unknown;
    /** Substitute every match of /pattern/flags via regexp2. Replacement uses .NET $1 / ${1} syntax. Backtracking engine — keep a timeout around untrusted input. */
    replace(arg0: string, arg1: string, arg2: string): unknown;
  };
  str: {
    /** Standard base64; URL-safe input is accepted via auto-detect. */
    base64Decode(...args: unknown[]): unknown;
    /** Standard base64 (with padding). */
    base64Encode(...args: unknown[]): unknown;
    /** Inverse of nl2br: <br>, <br/>, <br /> → '\n'. */
    br2nl(...args: unknown[]): unknown;
    /** Decode named and numeric HTML entities to their UTF-8 equivalents. */
    htmlEntityDecode(...args: unknown[]): unknown;
    /** Shortcut for pad(side: 'left'). */
    lpad(...args: unknown[]): unknown;
    /** Like trim, left side only. */
    ltrim(...args: unknown[]): unknown;
    /** Replace newlines with <br> (or <br/> when xhtml=true). */
    nl2br(...args: unknown[]): unknown;
    /** Canonicalise any mix of \r\n, \r, \n to the requested style ('lf' | 'crlf' | 'cr'). */
    normalizeNewlines(...args: unknown[]): unknown;
    /** Pad to `len` with `padChar` (default ' '). `side` is 'right' (default), 'left', or 'both'. */
    pad(...args: unknown[]): unknown;
    /** sprintf + write to stdout. */
    printf(...args: unknown[]): unknown;
    /** Rune-aware reversal — `reverse('café')` is `'éfac'`. */
    reverse(...args: unknown[]): unknown;
    /** Shortcut for pad(side: 'right'). */
    rpad(...args: unknown[]): unknown;
    /** Like trim, right side only. */
    rtrim(...args: unknown[]): unknown;
    /** Go's fmt verbs (%s, %d, %x, %.2f, %v, %t, %q, …) — not PHP's. */
    sprintf(...args: unknown[]): unknown;
    /** Remove HTML tags and decode common entities. */
    stripHtml(...args: unknown[]): unknown;
    /** Strip whitespace (or any char in the optional mask string) from both ends. */
    trim(...args: unknown[]): unknown;
    /** Inverse of urlEncode. */
    urlDecode(...args: unknown[]): unknown;
    /** Form-encoding ('+' for space). For path segments use encodeURIComponent (provided by goja). */
    urlEncode(...args: unknown[]): unknown;
  };
};

/** Binary-format codecs: compression, barcodes, check digits. */
declare const codec: {
  barcode: {
    /**
     * Available decode formats (qr / datamatrix / aztec / code128 / code39 / code93 / codabar / ean13 / ean8 / upca / upce / itf). PDF417 is encode-only.
     * @returns string[] — the twelve symbology names barcode.decode can recognise. PDF417 is absent (gozxing has no PDF417 decoder).
     */
    decodableFormats(): string[];
    /**
     * Decode a PNG/JPEG/WebP image to { format, text } via gozxing. Optional format hint skips the auto-detect walk. EAN/UPC need a quiet zone in the input. Async.
     * @param data Image bytes (PNG / JPEG / WebP). A string is treated as its raw UTF-8 bytes.
     * @param format Symbology hint (case-insensitive) from decodableFormats. When given, only that reader runs; otherwise every decoder is tried in priority order and the first hit wins.
     * @returns Promise<{ format: string, text: string }> — the detected symbology name and the decoded payload.
     */
    decode(data: string | Uint8Array | ArrayBuffer, format?: string): Promise<Record<string, unknown>>;
    /**
     * Render data into a PNG of the chosen format. opts.width / opts.height default to 256x256 (2D) or 400x120 (1D). opts.quietZone (true or px count) pads a white margin — required for EAN/UPC to decode. Async.
     * @param format Symbology (case-insensitive): qr / datamatrix / aztec / pdf417 / code128 / code39 / codabar / ean13 / ean8 / upca.
     * @param data Payload to encode. EAN/UPC require the exact digit count for the variant; the encoder validates content per symbology.
     * @param opts width / height set the output pixel dimensions (default 256x256 for 2D qr/datamatrix/aztec, 400x120 otherwise). quietZone pads a white margin: true uses 10% of width (min 10px), a number uses that many pixels per side, false/0/absent adds none. EAN/UPC need a quiet zone to be decodable.
     * @returns Promise<Uint8Array> — PNG image bytes.
     */
    encode(format: string, data: string, opts?: { width?: number, height?: number, quietZone?: boolean | number }): Promise<Uint8Array>;
    /**
     * Available encode formats (qr / datamatrix / aztec / pdf417 / code128 / code39 / codabar / ean13 / ean8 / upca).
     * @returns string[] — the ten symbology names accepted by barcode.encode.
     */
    formats(): string[];
  };
  checkdigit: {
    /**
     * Supported algorithms (luhn / isbn10 / isbn13 / ean13 / ean8 / upca).
     * @returns string[] — the six supported algorithm names. isbn13 is an alias for ean13 (same check-digit math).
     */
    algos(): string[];
    /**
     * Compute the missing trailing check digit for a partial input.
     * @param algo Algorithm name (case-insensitive, trimmed): luhn / isbn10 / isbn13 / ean13 / ean8 / upca.
     * @param partial The number WITHOUT its check digit (whitespace trimmed). Fixed-length algorithms expect exactly length-1 digits (e.g. 12 for ean13, 9 for isbn10).
     * @returns string — the single check digit ('0'–'9', or 'X' for isbn10 when the value is 10).
     */
    compute(algo: string, partial: string): string;
    /**
     * Diagnostic combining validate + compute: { valid, given, computed, … }.
     * @param algo Algorithm name (case-insensitive, trimmed): luhn / isbn10 / isbn13 / ean13 / ean8 / upca.
     * @param input The full number including its trailing check digit (whitespace trimmed).
     * @returns { algo, input, valid, given, computed } — algo/input echo the normalised arguments; given is the input's last character; computed is the recalculated check digit (empty when the input is too short or malformed to split); valid is true when given equals computed (case-insensitive).
     */
    inspect(algo: string, input: string): { algo: string, input: string, valid: boolean, given: string, computed: string };
    /**
     * Return whether the input passes the named algorithm's check digit.
     * @param algo Algorithm name (case-insensitive, trimmed): luhn / isbn10 / isbn13 / ean13 / ean8 / upca.
     * @param input The full number including its trailing check digit (whitespace trimmed). ISBN-10 may end in 'X'.
     * @returns boolean — true when the input's check digit is valid for the algorithm. Returns false (does not throw) for wrong length, non-digit characters, or an unknown algorithm.
     */
    validate(algo: string, input: string): boolean;
  };
  compression: {
    /**
     * Available compression algorithm names (gzip / deflate / zlib / bzip2 / zstd / brotli / lz4 / xz / snappy).
     * @returns string[] — the nine supported algorithm names, lowercase, in registration order.
     */
    algos(): string[];
    /**
     * Compress data with the named algorithm. Returns Uint8Array. Async.
     * @param algo Algorithm name (case-insensitive): gzip / deflate / zlib / bzip2 / zstd / brotli / lz4 / xz / snappy.
     * @param data Input bytes. Strings are interpreted as their UTF-8 byte sequence.
     * @returns Promise<Uint8Array> — the compressed bytes.
     */
    compress(algo: string, data: string | Uint8Array | ArrayBuffer): Promise<Uint8Array>;
    /**
     * Decompress data previously produced by compress (same algorithm name required). Returns Uint8Array. Async.
     * @param algo Algorithm name (case-insensitive), matching the one used to compress: gzip / deflate / zlib / bzip2 / zstd / brotli / lz4 / xz / snappy.
     * @param data Compressed input bytes.
     * @returns Promise<Uint8Array> — the original decompressed bytes.
     */
    decompress(algo: string, data: string | Uint8Array | ArrayBuffer): Promise<Uint8Array>;
  };
  perl: {
    /**
     * Perl Data::Dumper-style dump ($VAR1 = … ;), normalized indentation. JS booleans emit the JSON::XS::Boolean blessed-ref form (opts.perlBoolClass).
     * @param value Any JSON-like value (see php.serialize). Arrays/objects emit as Perl array/hash refs; class-key objects emit as blessed refs.
     * @param opts perlBoolClass names the blessed class emitted for JS booleans (default "JSON::XS::Boolean"). indent overrides the indentation step. classKey overrides the class-name sentinel (default "__class").
     * @returns string — a Data::Dumper-style dump ($VAR1 = ... ;) with normalized indentation.
     */
    dumper(value: unknown, opts?: { classKey?: string, perlBoolClass?: string, indent?: string }): string;
    /**
     * Read Data::Dumper output back. Blessed scalar refs in the JSON bool family decode to booleans; bare 1/0 stay numbers; cycles throw.
     * @param input Data::Dumper output to parse back (a $VARn = ... ; assignment or a bare value).
     * @param opts classKey sets the sentinel property used to tag decoded blessed refs (default "__class"). The JSON bool family (JSON::XS::Boolean, JSON::PP::Boolean, Types::Serialiser::Boolean) decodes to JS booleans regardless.
     * @returns unknown — the decoded value. Blessed scalar refs in the JSON-bool family become JS booleans; bare 1/0 stay numbers; other blessed refs carry the classKey sentinel.
     */
    parseDumper(input: string, opts?: { classKey?: string, perlBoolClass?: string, indent?: string }): unknown;
  };
  php: {
    /**
     * Best-effort read of var_dump() output. Throws on lossy markers (*RECURSION*, truncation, visibility-annotated props).
     * @param input PHP var_dump() output to parse back.
     * @param opts classKey sets the sentinel property used to tag decoded objects (default "__class").
     * @returns unknown — the reconstructed value (best-effort; var_dump is a lossy format).
     */
    parseVarDump(input: string, opts?: { classKey?: string, perlBoolClass?: string, indent?: string }): unknown;
    /**
     * Read a var_export() literal (arrays, scalars, NULL, \Cls::__set_state) back to a value.
     * @param input A PHP var_export() literal: array(...), scalars, NULL, or \Cls::__set_state(array(...)).
     * @param opts classKey sets the sentinel property used to tag decoded __set_state objects (default "__class").
     * @returns unknown — the decoded value; \Cls::__set_state objects become plain objects carrying the classKey sentinel.
     */
    parseVarExport(input: string, opts?: { classKey?: string, perlBoolClass?: string, indent?: string }): unknown;
    /**
     * PHP serialize(): encode a value to PHP's canonical serialization string. Objects use the __class sentinel; cycles throw.
     * @param value Any JSON-like value: null, boolean, number, string, array, or plain object. An object carrying the class-key sentinel (opts.classKey, default "__class") encodes as a PHP object (O:).
     * @param opts classKey overrides the class-name sentinel property (default "__class"). indent / perlBoolClass are unused by serialize.
     * @returns string — the PHP serialize() string (e.g. a:1:{...}).
     */
    serialize(value: unknown, opts?: { classKey?: string, perlBoolClass?: string, indent?: string }): string;
    /**
     * PHP unserialize(): decode a serialize() string back to a value. r:/R: references resolve to shared objects (DAGs); cycles throw.
     * @param input A PHP serialize() string.
     * @param opts classKey sets the sentinel property used to tag decoded PHP objects (default "__class").
     * @returns unknown — the decoded value. PHP objects become plain objects carrying the classKey sentinel; r:/R: references rebuild as shared object identities (DAGs).
     */
    unserialize(input: string, opts?: { classKey?: string, perlBoolClass?: string, indent?: string }): unknown;
    /**
     * PHP var_dump(): human-readable debug output. String lengths are byte counts.
     * @param value Any JSON-like value (see php.serialize).
     * @param opts indent overrides the default indentation step. classKey overrides the class-name sentinel (default "__class").
     * @returns string — var_dump()-style output. String lengths in the output are byte counts, matching PHP.
     */
    varDump(value: unknown, opts?: { classKey?: string, perlBoolClass?: string, indent?: string }): string;
    /**
     * PHP var_export(): emit valid PHP code for a value. opts.indent overrides the 2-space step.
     * @param value Any JSON-like value (see php.serialize). Objects with the class-key sentinel emit as \Cls::__set_state(...).
     * @param opts indent overrides the default 2-space indentation step. classKey overrides the class-name sentinel (default "__class").
     * @returns string — valid PHP source, the kind var_export() prints.
     */
    varExport(value: unknown, opts?: { classKey?: string, perlBoolClass?: string, indent?: string }): string;
  };
};

/** Filesystem operations: path manipulation and archive create/extract. */
declare const fs: {
  archive: {
    /**
     * Create a zip / tar / tar.gz at destPath from a list of paths. Format inferred from extension.
     * @param destPath Output archive path. Format is inferred from the extension: .zip, .tar, .tar.gz, or .tgz.
     * @param sources Non-empty array of inputs. A bare string uses the disk path as-is and its basename inside the archive; an object overrides the in-archive name via name. Directory sources are recursed (the directory's basename becomes the archive subdir). Archive paths always use forward slashes.
     * @returns Promise<{ path: string, format: string, entries: string[], bytes?: number }> — path is destPath, format is the inferred format ("zip" | "tar" | "tar.gz"), entries lists the file paths written (directories excluded), and bytes is the final archive size when stat succeeds.
     */
    create(destPath: string, sources: (string | { path: string, name?: string })[]): Promise<Record<string, unknown>>;
    /**
     * Extract a zip / tar / tar.gz to destDir. opts.overwrite controls O_EXCL behaviour.
     * @param archivePath Path to the archive. Format is inferred from its extension (.zip, .tar, .tar.gz, .tgz).
     * @param destDir Destination directory; created (recursively) if absent. All entries are confined to this directory via zip-slip / tar-slip protection.
     * @param opts overwrite (default false) clobbers existing files; when false, an entry colliding with an existing file fails the call (O_EXCL).
     * @returns Promise<{ path: string, format: string, dest: string, entries: string[] }> — path is archivePath, format is the inferred format, dest is destDir, and entries lists the extracted entry names (regular files only).
     */
    extract(archivePath: string, destDir: string, opts?: { overwrite?: boolean }): Promise<Record<string, unknown>>;
  };
  path: {
    /**
     * Final segment of a path; optional suffix is stripped if it matches.
     * @param path A forward-slash path. Trailing slashes are stripped before taking the last segment.
     * @param suffix Trailing suffix to remove from the result (e.g. an extension). Only stripped when it matches and is not the entire segment; a non-matching or empty suffix is ignored.
     * @returns string — the last path segment, with suffix removed when it applies.
     */
    basename(path: string, suffix?: string): string;
    /**
     * Directory portion of a path. POSIX-style; trailing slashes are stripped.
     * @param path A forward-slash path. On Windows, normalise separators yourself first.
     * @returns string — everything up to (not including) the final slash; "." when the path has no directory component, "/" for a rooted single segment.
     */
    dirname(path: string): string;
  };
};

/** Network clients and probes: HTTP, TCP/DNS/TLS/NTP/WHOIS probes, netstatus, email auth, browser-style sessions. */
declare const net: {
  browser: {
    /** Open a stateful HTTP session: { setUserAgent, setHeader, get, post, cookies }. Cookie jar + default headers persist across requests (like a browser). */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  capture: {
    /** List the host's network interfaces synchronously: net.capture.interfaces() → array of { name, addresses: string[], up, loopback }. Pure-Go (no privileges, all platforms). */
    interfaces(...args: unknown[]): unknown;
    /** Live packet capture: net.capture.open({ iface, promisc?, snaplen?, filter? }, pkt => {…}) → Promise<{ iface, link, close() }>. Linux + macOS only (Windows rejects); needs root / CAP_NET_RAW (Linux) or /dev/bpf access (macOS). promisc defaults true. The handler is called per frame with a decoded packet { ts, length, captureLength, link, eth?, ip?, tcp?, udp?, icmp?, payload?, bytes }. Optional filter is a tcpdump-like expression string (e.g. 'tcp and port 80'), evaluated post-decode in userspace — NOT a kernel BPF program, so it skips the JS callback for non-matching packets but does not avoid the kernel→userspace copy. Supports tcp/udp/icmp/ip/ip6, host/src host/dst host, port/src port/dst port, and/or/not + parens, implicit-and between juxtaposed primaries. No CIDR (net X/Y) or portrange yet; a malformed expression makes open reject. close() returns Promise<void>. Pure-Go gopacket (no libpcap/cgo). */
    open(...args: unknown[]): unknown;
    /** Read a .pcap / .pcapng file: net.capture.openFile(path, pkt => {…}, opts?) → Promise<void>. Calls the handler once per decoded packet (same shape as capture.open) and resolves at EOF. Offline; no privileges. opts is an optional trailing arg { filter? } — the 2-arg form still works; filter is the same tcpdump-like expression string as capture.open (post-decode/userspace, not kernel BPF; no CIDR/portrange; malformed → rejects). */
    openFile(...args: unknown[]): unknown;
    /** Write raw frames to a .pcap file: net.capture.toFile(path, { linkType?, snaplen? }) → { write(bytes, { ts? }), close() }. write appends a raw frame (Uint8Array); ts (ms) overrides the timestamp. close() flushes and returns Promise<void>. Offline; no privileges. */
    toFile(...args: unknown[]): unknown;
  };
  email: {
    /** Run all five email probes in parallel — five-way handshake aggregate. */
    all(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe BIMI: TXT(<selector>._bimi.<domain>); selector defaults to 'default'. */
    bimi(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Query TXT(_dmarc.<domain>) and parse policy / pct / rua / ruf tags. */
    dmarc(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe MTA-STS: TXT(_mta-sts.<domain>) plus the fetched policy file. */
    mtaSts(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Send an outbound email: net.email.send({to, from, subject, body, html?, attachments?, headers?, server: {host, port?, auth?, tls?}, timeout?}) → Promise<{accepted: string[], rejected: [{address, reason}]}>. One TCP connection per call; per-recipient outcome captured. Transport failures throw; per-RCPT rejections surface in the result. TLS modes: starttls (default), tls, none. */
    send(...args: unknown[]): Promise<{ accepted: string[]; rejected: { address: string; reason: string }[] }>;
    /** Query TXT(<domain>) for SPF, return record + parsed mechanisms + all-policy. */
    spf(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe TLS-RPT: TXT(_smtp._tls.<domain>) and parse rua. */
    tlsRpt(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  http: {
    /** Perform an HTTP GET with a 5-second default timeout. Returns { status, body }. */
    get(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Perform an HTTP POST with a 5-second default timeout. Returns { status, body }. */
    post(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Full HTTP client: method, url, opts {headers, body, timeout, retry, follow, username, password}. Returns {status, ok, headers, body, url}. 4xx/5xx dont throw; retry covers transport errors + 5xx. */
    request(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  icmp: {
    /** Open a raw ICMP socket: net.icmp.open(opts?) → Promise<handle>. Requires root / CAP_NET_RAW (open rejects otherwise). opts { network?: 'ip4'|'ip6' (default 'ip4'), readBuffer? }. handle.send({ to, type?, code?, id?, seq?, payload? }) builds an Echo-shaped body (non-Echo bodies not modelled); push/callback model — onMessage(cb) events carry { address, type, code }; onClose(cb)/onError(cb); handle.network/local; handle.close(). */
    open(...args: unknown[]): unknown;
  };
  netstatus: {
    /** Run DNS / TCP / TLS / HTTP against one host concurrently. Returns { reachable, dns, tcp, tls, http } — each sub-probe ok+error; reachable = dns.ok AND tcp.ok. Sub-failures are data, not throws. */
    check(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  probe: {
    /** Look up A / AAAA / MX / TXT / CNAME / NS records. Default: all five. */
    dns(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Query an NTPv4 server (UDP 123) and report offset, RTT, stratum, root delay / dispersion. */
    ntp(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Reachability probe. mode tcp (default; dials host:port) or icmp (needs raw-socket privileges). Returns { sent, received, lossPercent, minMs, avgMs, maxMs }. Unreachable = received 0, no throw. */
    ping(...args: unknown[]): Promise<{ host: string; ip: string; mode: string; sent: number; received: number; lossPercent: number; minMs: number; avgMs: number; maxMs: number }>;
    /** SMTP capability probe (no mail sent). EHLO + parse extensions. Returns { banner, ehloDomain, extensions, starttls, authMechanisms, sizeLimit }. Connection failures throw. */
    smtp(...args: unknown[]): Promise<{ host: string; port: string; banner: string; ehloDomain: string; extensions: string[]; starttls: boolean; authMechanisms: string[]; sizeLimit: number }>;
    /** Dial a TCP target and report latency + resolved IP. Default timeout 5s. */
    tcp(...args: unknown[]): Promise<{ host: string; port: number; ip: string; latencyMs: number }>;
    /** Open a TLS connection (InsecureSkipVerify; for probing only) and return the cert chain summary. */
    tls(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Two-hop WHOIS via the IANA referral, returning the parsed record plus the raw response text. */
    whois(...args: unknown[]): Promise<Record<string, unknown>>;
    /** WebSocket handshake probe. Opens ws://wss:// connection, optional ping/pong RTT. Returns { connected, subprotocol, status, handshakeMs, pingMs }. Failed handshake throws. */
    wss(...args: unknown[]): Promise<{ url: string; connected: boolean; subprotocol: string; status: number; handshakeMs: number; pingMs: number }>;
  };
  tcp: {
    /** Open a TCP client socket: net.tcp.connect(host, port, opts?) → Promise<handle>. Push/callback read model — handle.onData(cb)/onClose(cb)/onError(cb) register listeners; handle.write(data) sends (string→UTF-8 / Uint8Array); handle.remote/local are the peer/local addresses; handle.close() shuts down. opts { timeout?, readBuffer? }. */
    connect(...args: unknown[]): unknown;
  };
  udp: {
    /** Open a UDP socket: net.udp.open(opts) → Promise<handle>. Connected mode { host, port } exposes send(data); bound mode { bind: ':9999' } exposes sendTo(data, host, port) and tags inbound events with { address, port }. Push/callback model — onMessage(cb)/onClose(cb)/onError(cb); handle.local is the bound address; handle.close() shuts down. opts also takes readBuffer?. */
    open(...args: unknown[]): unknown;
  };
};

/** Database / KV / directory clients: SQLite, PostgreSQL, MySQL/MariaDB, SQL Server, Redis, memcached, LDAP, dict. */
declare const db: {
  clickhouse: {
    /** Connect to ClickHouse via the pure-Go clickhouse-go v2 driver. Arg is a clickhouse:// URL DSN string or an options object { host, port, user, password, database, secure }. Returns the shared SQL handle { exec, query, queryValue, begin, prepare, close }. Uses ? placeholders; default native port 9000 (set secure:true for TLS). Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  dict: {
    /** RFC 2229 DICT word lookup. define(host, word, opts?) -> { word, found, definitions: [{ db, dbName, text }] }. found:false on no match (not an error). */
    define(...args: unknown[]): Promise<{ word: string; found: boolean; definitions: { db: string; dbName: string; text: string }[] }>;
    /** RFC 2229 word match. match(host, word, opts?) -> { word, matches: [{ db, word }] }. opts.strategy (default prefix), opts.database, opts.port (default 2628). */
    match(...args: unknown[]): Promise<{ word: string; matches: { db: string; word: string }[] }>;
  };
  ldap: {
    /** Dial LDAP (ldap://host:port), anonymous bind (or opts.bindDN/password). Returns { rootDSE, search, close }. search(baseDN, filter, attrs?) -> entries; rootDSE -> server metadata. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  memcached: {
    /** Connect to memcached (host:port). Returns { get, set, delete }. get -> string or null (miss); delete -> bool (existed). set(key, value, expirySeconds?). */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  mssql: {
    /** Connect to Microsoft SQL Server via the pure-Go go-mssqldb driver. Arg is a sqlserver:// URL DSN string or an options object { host, port, user, password, database }. Returns the shared SQL handle. Uses @p1,@p2,… placeholders. Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  mysql: {
    /** Connect to MySQL/MariaDB via the pure-Go go-sql-driver. Arg is a go-sql-driver DSN string (user:pass@tcp(host:port)/db) or an options object { host, port, user, password, database }. Returns the shared SQL handle. Uses ? placeholders. Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  oracle: {
    /** Connect to Oracle via the pure-Go go-ora driver (no cgo). Arg is an oracle:// URL DSN string or an options object { host, port, user, password, database } where database is the service name. Returns the shared SQL handle. Uses :1,:2,… bind placeholders; default port 1521. Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  postgres: {
    /** Connect to PostgreSQL via the pure-Go pgx driver. Arg is a libpq DSN/URL string or an options object { host, port, user, password, database, sslmode }. Returns the shared SQL handle { exec, query, queryValue, begin, prepare, close }. Uses $1,$2,… placeholders. Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  redis: {
    /** Connect to Redis (redis://...). Returns { do, ping, close }. do(cmd, ...args) runs any RESP command; missing key -> null. Pings on open to surface bad addresses. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  sqlite: {
    /** Open a SQLite database (':memory:' or a file path; created if absent). Resolves to a handle { exec, query, queryValue, begin, prepare, close }. Connection is Ping-ed before resolving. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
};

/** Subprocess and external-CLI / service wrappers: shell, git, gh, AI providers. */
declare const services: {
  ai: {
    /**
     * Which of claude / codex / copilot / gemini are on PATH, in preference order.
     * @returns string[] — the subset of supported AI CLIs found on PATH, in preference order (claude, codex, copilot, gemini); an empty array when none are installed. Synchronous (not a Promise).
     */
    providers(): string[];
    /**
     * Run a one-shot prompt through a provider. opts { prompt (required), provider?, system?, context?, timeout? }. Returns { provider, output, exitCode }. Non-zero exit is data; no provider throws.
     * @param opts prompt is required. provider names the CLI to use; when omitted, the first provider on PATH (in preference order) is chosen. system and context are prepended to the prompt as "System: …" / "Context: …" blocks (a portable substitute for each CLI's own flags). timeout in ms (default 120000).
     * @returns Promise<{ provider: string, output: string, exitCode: number }> — provider is the CLI that ran; output is its trimmed stdout (or stderr when stdout is empty on a non-zero exit); exitCode is 0 on success.
     */
    send(opts: { prompt: string, provider?: "claude" | "codex" | "copilot" | "gemini", system?: string, context?: string, timeout?: number }): Promise<Record<string, unknown>>;
  };
  exec: {
    /**
     * Make an HTTP request by shelling out to recon (preferred) or curl (fallback). 4xx/5xx resolve as status; transport errors and timeouts throw. opts.backend = 'auto' | 'recon' | 'curl'.
     * @param method HTTP verb (GET, POST, PUT, DELETE, PATCH, HEAD); lower-case input is uppercased before forwarding.
     * @param url Target URL; must be fully qualified (the backend requires a scheme + host).
     * @param opts headers emits one -H "Name: Value" per entry. body is written to a temp file and sent via --data-binary so CR/LF stay intact. timeout in ms (default 30000). follow toggles -L to follow 3xx redirects. insecure toggles -k to skip TLS verification. backend picks the tool: 'auto' (default) prefers recon then curl; 'recon' or 'curl' require that specific binary on PATH.
     * @returns Promise<{ status: number, headers: Record<string, string>, body: string, durationMs: number, backend: "recon" | "curl" }> — status is the final HTTP status code; headers have lower-cased names (last response block on a redirect chain); body is the UTF-8 decoded response body; backend is whichever tool ran.
     */
    http(method: string, url: string, opts?: { headers?: Record<string, string>, body?: string, timeout?: number, follow?: boolean, insecure?: boolean, backend?: "auto" | "recon" | "curl" }): Promise<Record<string, unknown>>;
    /**
     * Run a subprocess and wait for it to exit. String cmd → /bin/sh -c (or `cmd /C` on Windows); array cmd → argv (no shell). Non-zero exits resolve normally; spawn failures and timeouts throw.
     * @param cmd A string is passed verbatim to the host shell (/bin/sh -c on Unix, cmd /C on Windows) so quoting, pipes, and redirects work. A string[] is treated as argv: argv[0] is run directly with no shell, so use this form when arguments contain whitespace or shell metacharacters you don't want re-interpreted.
     * @param opts timeout in ms (default 30000); on expiry the process tree is killed and the call throws. cwd sets the working directory. stdin is fed to the process's standard input. env entries are merged on top of the inherited environment (they do not replace it). pane (a tui.pane name or Pane handle) streams stdout+stderr live into a TUI pane — in that mode the result's stdout/stderr strings stay empty.
     * @returns Promise<{ stdout: string, stderr: string, exitCode: number, success: boolean, durationMs: number }> — stdout/stderr are captured (empty when streamed to a pane); exitCode is 0 on success; success is exitCode === 0; durationMs is wall-clock spawn-to-exit time.
     */
    shell(cmd: string | string[], opts?: { timeout?: number, cwd?: string, stdin?: string, env?: Record<string, string>, pane?: string | Pane }): Promise<Record<string, unknown>>;
  };
  gh: {
    /**
     * Probe gh's auth state. Missing gh / unauthenticated resolve with { authenticated: false, … } — only context cancellation throws.
     * @returns Promise<{ authenticated: boolean, user: string, raw: string }> — authenticated is true only when `gh api user` succeeds; user is the resolved login ("" when not authenticated); raw is the login on success or the underlying gh error / "gh not on PATH" otherwise.
     */
    authStatus(...args: unknown[]): Promise<{ authenticated: boolean; user: string; raw: string }>;
    /**
     * List pull requests on the cwd's repo (or opts.cwd). Defaults: open state, limit 30. Filters: state / limit / author.
     * @param opts cwd selects the repo (defaults to the engine's working directory, which gh uses to detect the repo). state filters by PR state ("open" default, "closed", "merged", "all"). limit caps results (default 30; must be positive). author filters to PRs opened by that login.
     * @returns Promise<Array<{ number: number, title: string, state: string, author: string, headRefName: string, baseRefName: string, url: string, createdAt: string, updatedAt: string }>> — one object per PR; author is flattened from gh's { login } wrapper to the bare login string; createdAt/updatedAt are ISO 8601 timestamps.
     */
    prList(opts?: { cwd?: string, state?: string, limit?: number, author?: string }): Promise<Record<string, unknown>[]>;
    /**
     * Repo metadata. With no arg uses cwd's repo; pass 'owner/name' for any repo gh can see. owner + defaultBranch are pre-flattened.
     * @param repo "owner/name" of any repo gh can access. Omit (or pass opts as the first arg) to view the repo detected from cwd.
     * @param opts cwd selects the checkout gh uses to detect the current repo when repo is omitted.
     * @returns Promise<{ name: string, owner: string, description: string, url: string, defaultBranch: string, visibility: string }> — owner is flattened from gh's { login } wrapper to the bare login; defaultBranch is flattened from defaultBranchRef.name ("" if absent); key order matches gh's output.
     */
    repoView(repo?: string, opts?: { cwd?: string }): Promise<Record<string, unknown>>;
  };
  git: {
    /**
     * Stage one path (string) or several (string[]).
     * @param paths Path or paths to stage. Passed after a `--` separator so paths that look like flags (-foo) are handled literally.
     * @param opts cwd selects the checkout; defaults to the engine's working directory.
     * @returns Promise<{ paths: string[] }> — the list of paths that were staged.
     */
    add(paths: string | string[], opts?: { cwd?: string }): Promise<{ paths: string[] }>;
    /**
     * Current branch (empty when HEAD is detached) plus the list of local branches.
     * @param opts cwd selects the checkout to inspect; defaults to the engine's working directory.
     * @returns Promise<{ current: string, detached: boolean, all: string[] }> — current is the checked-out branch name ("" when detached); detached is true on a detached HEAD; all lists every local branch (refs/heads) by short name.
     */
    branch(opts?: { cwd?: string }): Promise<{ current: string; detached: boolean; all: string[] }>;
    /**
     * Create a commit; returns the post-commit HEAD SHA. opts.allowEmpty toggles --allow-empty.
     * @param message Commit message (passed as a single -m argument).
     * @param opts cwd selects the checkout. allowEmpty adds --allow-empty so a commit succeeds with no staged changes (release markers, etc.); defaults to false.
     * @returns Promise<{ sha: string }> — sha is the full SHA of the newly created HEAD commit.
     */
    commit(message: string, opts?: { cwd?: string, allowEmpty?: boolean }): Promise<{ sha: string }>;
    /**
     * Aggregate { files, insertions, deletions } from `git diff --shortstat`. Default revRange HEAD~1..HEAD.
     * @param opts cwd selects the checkout. revRange is the diff range (default "HEAD~1..HEAD", the last commit).
     * @returns Promise<{ files: number, insertions: number, deletions: number }> — counters parsed from git diff --shortstat. An empty diff returns all zeros.
     */
    diffStat(opts?: { cwd?: string, revRange?: string }): Promise<{ files: number; insertions: number; deletions: number }>;
    /**
     * True iff `git status --porcelain` is empty.
     * @param opts cwd selects the checkout; defaults to the engine's working directory.
     * @returns Promise<boolean> — true when the working tree has no staged, unstaged, or untracked changes.
     */
    isClean(opts?: { cwd?: string }): Promise<boolean>;
    /**
     * Recent commits as { sha, shortSha, author, email, timestamp, subject }. opts.limit / opts.revRange.
     * @param opts cwd selects the checkout. limit caps the number of commits (default 50; must be positive). revRange selects the range/ref to walk (default "HEAD").
     * @returns Promise<Array<{ sha: string, shortSha: string, author: string, email: string, timestamp: number, subject: string }>> — newest first; timestamp is the author Unix epoch seconds; subject is the commit's first line.
     */
    log(opts?: { cwd?: string, limit?: number, revRange?: string }): Promise<{ sha: string; shortSha: string; author: string; email: string; timestamp: number; subject: string }[]>;
    /**
     * Full 40-char SHA for the given rev. Invalid refs throw.
     * @param rev Any revision git understands (branch, tag, HEAD, short SHA, HEAD~2, etc.).
     * @param opts cwd selects the checkout; defaults to the engine's working directory.
     * @returns Promise<string> — the full 40-character commit SHA the rev resolves to.
     */
    revParse(rev: string, opts?: { cwd?: string }): Promise<string>;
    /**
     * Escape hatch: run any `git <args>`, get { stdout, stderr, exitCode } — exitCode is data, not a throw.
     * @param args git arguments (without the leading "git"), e.g. ["tag", "--list"]. A bare string is treated as a single argument.
     * @param opts cwd selects the checkout; defaults to the engine's working directory.
     * @returns Promise<{ stdout: string, stderr: string, exitCode: number }> — captured streams plus git's exit code, so callers can react to any exit status without try/catch.
     */
    runText(args: string | string[], opts?: { cwd?: string }): Promise<{ stdout: string; stderr: string; exitCode: number }>;
    /**
     * Parsed `git status --porcelain` entries: { path, indexStatus, workingStatus }.
     * @param opts cwd selects the checkout; defaults to the engine's working directory.
     * @returns Promise<Array<{ path: string, indexStatus: string, workingStatus: string }>> — one entry per changed path; indexStatus / workingStatus are the porcelain v1 X / Y status characters (e.g. "M", "A", "?"). An empty array means a clean tree.
     */
    status(opts?: { cwd?: string }): Promise<{ path: string; indexStatus: string; workingStatus: string }[]>;
  };
};

/** Multi-pane terminal UI: layout, pane, write, focus. */
declare const tui: {
  /** Declare the pane layout for this Run. Tree nodes: { name, title?, weight? } (leaf), { rows: [...], weight? } (vertical split), { cols: [...], weight? } (horizontal split). Throws on duplicate names, empty rows/cols, unknown keys, or under --watch. */
  layout(...args: unknown[]): unknown;
  /** Return a Pane handle for a declared pane. Throws if the name wasn't in the layout. Handle methods: write(text), writeln(text), clear(), title(text). services.exec.shell({pane}) streams subprocess I/O into a pane. */
  pane(...args: unknown[]): unknown;
};

/** Network servers: HTTP/HTTPS listeners with routing, middleware, static files, WebSocket upgrade. */
declare const server: {
  http: {
    /** Bind an HTTP listener: server.http.listen({port, host?, routes, use?}) → handle with .address, .close(), .stopped Promise. routes is a map of stdlib http.ServeMux patterns ('GET /users/{id}') to handlers (req, res) => res.json({...}) or {use: [...], handler: fn} for per-route middleware. Handlers can call res.upgradeWebSocket(opts?) to hijack the connection and return an AsyncIterable<WSMessage> with .send / .close — `for await (const msg of ws)` walks frames; msg is {type:'text',text} or {type:'binary',bytes:Uint8Array}. */
    listen(...args: unknown[]): unknown;
    /** Static-file mount: server.http.static({dir, stripPrefix, index?, etag?}) → handler. Assign to a wildcard route (GET /assets/{rest...}). Internally stdlib http.FileServer with stripPrefix; ETag/Last-Modified/range requests work; no directory listing. */
    static(...args: unknown[]): unknown;
  };
  https: {
    /** Like server.http.listen plus required cert/key (file paths OR inline PEM strings). No autocert; no self-signed magic. */
    listen(...args: unknown[]): unknown;
    /** Like server.http.static; same options. */
    static(...args: unknown[]): unknown;
  };
  smtp: {
    /** Bind an SMTP listener: server.smtp.listen({port, hostname?, handlers: {onMail, onRcpt, onData}, auth?, starttls?, allowInsecureAuth?, maxMessageBytes?, maxRecipients?, sessionTimeout?}) → handle with .address, .close(), .stopped Promise. Handlers receive (envelope, …) per stage; return true/undefined to accept, false to reject, a string for a 550 reason, throw for 451 temp-fail. onData receives a parsed Message with text/html bodies, attachments, and raw bytes. */
    listen(...args: unknown[]): unknown;
  };
  tcp: {
    /** Bind a raw TCP server: server.tcp.listen({port, host?, readBuffer?}, conn => {…}) → handle { address: 'tcp/host:port', close() }. The connection handler runs once per accepted socket; conn is the SAME handle shape as net.tcp.connect — onData(cb) (cb gets {bytes, text}), onClose(cb), onError(cb), write(data) (string or Uint8Array), close(), and remote/local addresses. Synchronous bind (throws on bind error); port:0 binds an OS-chosen ephemeral port. Emits a READY line under `sercon serve` and joins graceful shutdown. */
    listen(...args: unknown[]): unknown;
  };
  udp: {
    /** Bind a raw UDP server: server.udp.listen({port, host?}, (msg, reply) => {…}) → handle { address: 'udp/host:port', close() }. The handler runs once per inbound datagram; msg is {bytes, text, address, port} (the sender) and reply(data) (string or Uint8Array) sends a datagram back to that sender, returning a Promise. Synchronous bind (throws on bind error); port:0 binds an OS-chosen ephemeral port. Emits a READY line under `sercon serve` and joins graceful shutdown. */
    listen(...args: unknown[]): unknown;
  };
};

