// AUTO-GENERATED by scriptengine.Engine.WriteTypes — do not edit by hand.
// Reserved globals: codec, console, crypto, db, fs, net, runtime, server, services, text, tui.

/** Browser/Node-style console shim: log/info/debug to stdout, warn/error to stderr. For porting scripts; runtime.log is the native equivalent. */
declare const console: {
  /** Alias of console.log — stringified arguments, space-joined, to stdout. */
  debug(...args: unknown[]): unknown;
  /** Like console.log but writes to stderr. */
  error(...args: unknown[]): unknown;
  /** Alias of console.log — stringified arguments, space-joined, to stdout. */
  info(...args: unknown[]): unknown;
  /** Print a space-joined line of the arguments to stdout. Primitives print raw; objects/arrays render as JSON. Browser/Node-compatible; same output as runtime.log. */
  log(...args: unknown[]): unknown;
  /** Like console.log but writes to stderr. */
  warn(...args: unknown[]): unknown;
};

/** Script-host scaffolding: logging, assertions, time, environment, runtime.argv. */
declare const runtime: {
  /** Per-script argument vector: [programName, scriptPath, ...userArgs]. argv[0] is the program name (sercon), argv[1] is the running script path, and any args after `--` on the command line start at argv[2]. */
  argv: string[];
  assert: {
    /** Throw when actual != expected (strict equality on primitives, deep equality on objects). Optional msg appears in the error. */
    equal(arg0: unknown, arg1: unknown, arg2: unknown[]): void;
    /** Throw when cond is falsy. Optional msg appears in the error. */
    ok(arg0: unknown, arg1: unknown[]): void;
  };
  env: {
    /** Read an environment variable. Returns undefined when unset (not empty string). */
    get(...args: unknown[]): unknown;
  };
  /** Print one space-separated line of the arguments to stdout. Primitives print raw; objects/arrays render as JSON (circular refs fall back to [object Object]). The script-side equivalent of console.log. */
  log(...args: unknown[]): unknown;
  time: {
    /** Format a unix-ms timestamp through strftime tokens. Optional IANA tz (e.g. 'Europe/Stockholm'); default is the host's local zone. */
    format(...args: unknown[]): unknown;
    /** Wall-clock milliseconds since the Unix epoch. */
    nowMs(): number;
    /** Resolve after `ms` milliseconds. Cancellable via the engine timeout. */
    sleep(...args: unknown[]): Promise<unknown>;
  };
};

/** Hashing, JWT, age encryption — anything that produces a digest, signature, or ciphertext. */
declare const crypto: {
  encrypt: {
    /** Open a payload with one of the supplied identities. Routes to age or PGP based on the identity / ciphertext format. age: binary or armored auto-detected. Wrong identity throws. */
    decrypt(arg0: unknown, arg1: unknown): unknown;
    /** Classify a recipient / identity string. Returns { backend: 'age'|'pgp'|'unknown', kind?: 'public'|'private' }. Pure prefix matching; no parsing or I/O. */
    detectBackend(arg0: string): unknown;
    /** Seal data to recipients. age public keys (age1...) → age backend (opts.armored for ASCII); PGP public-key blocks → PGP backend (always armored). Auto-dispatched on key format. Multi-recipient: any listed identity decrypts. */
    encrypt(arg0: unknown, arg1: unknown, arg2: unknown): unknown;
    /** Generate a fresh age X25519 keypair. Returns { publicKey: 'age1...', privateKey: 'AGE-SECRET-KEY-1...' }. */
    keygen(): unknown;
    /** Generate a PGP keypair (RSA 2048). opts.name / opts.email populate the user ID. Returns armored { publicKey, privateKey } blocks. encrypt/decrypt auto-route to PGP when they see these. */
    keygenPgp(arg0: unknown): unknown;
    /** Re-encrypt for a new recipient set without exposing plaintext to JS. Output format defaults to match the input; opts.armored forces. Internal decrypt+encrypt loop. */
    rekey(arg0: unknown, arg1: unknown, arg2: unknown, arg3: unknown): unknown;
  };
  hash: {
    /** BLAKE3 hex digest (32-byte output, lukechampine.com/blake3). */
    blake3(...args: unknown[]): unknown;
    /** CRC-32 (IEEE polynomial), zero-padded to 8 hex chars. */
    crc32(...args: unknown[]): unknown;
    /** MD5 hex digest of a UTF-8 input. Avoid for security purposes — exposed for compatibility with legacy fingerprints. */
    md5(...args: unknown[]): unknown;
    /** SHA-1 hex digest of a UTF-8 input. Avoid for security purposes. */
    sha1(...args: unknown[]): unknown;
    /** SHA-256 hex digest of a UTF-8 input. */
    sha256(...args: unknown[]): unknown;
    /** SHA-384 hex digest of a UTF-8 input. */
    sha384(...args: unknown[]): unknown;
    /** SHA-3 256-bit hex digest. The underscore in the name matches recon's binding. */
    sha3_256(...args: unknown[]): unknown;
    /** SHA-3 512-bit hex digest. */
    sha3_512(...args: unknown[]): unknown;
    /** SHA-512 hex digest of a UTF-8 input. */
    sha512(...args: unknown[]): unknown;
  };
  jwt: {
    /** Sign a claims object. secret is raw bytes for HS*; PEM-encoded private key for RS*/PS*/ES*/EdDSA; or a JWK JSON object (kty picks the key type) for any algorithm. opts.algorithm defaults to HS256. */
    sign(arg0: Record<string, unknown>, arg1: string, arg2: unknown): unknown;
    /** Verify signature + standard claims (exp/nbf/iat) + optional aud/iss. secret accepts raw bytes / PEM public key / JWK. Set opts.algorithm for the algo-confusion guard. Resolves { valid:true, claims } or { valid:false, reason }. */
    validate(arg0: string, arg1: string, arg2: unknown): unknown;
    /** Decode header + payload WITHOUT verifying the signature. Useful for inspection / debugging auth flows. Malformed input throws. */
    view(arg0: string): unknown;
  };
};

/** String / regex / charset / data manipulation — all text-shaped transforms. */
declare const text: {
  charset: {
    /** Decode bytes in a named charset to a UTF-8 string. */
    decode(...args: unknown[]): Promise<string>;
    /** Detect the most-likely charset of a byte sequence (saintfish/chardet). Returns top guess + candidates. */
    detect(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Encode a UTF-8 string to bytes in the named charset. */
    encode(...args: unknown[]): Promise<Uint8Array>;
  };
  diff: {
    /** Unified-diff two text inputs. opts: context (default 3), fromFile / toFile (default 'a' / 'b'). Binary inputs return { binary: true } with an empty diff. */
    compare(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  jq: {
    /** Run a jq filter over data and return the first emitted value (or null). */
    query(...args: unknown[]): Promise<unknown>;
    /** Run a jq filter and drain the iterator into an array. */
    queryAll(...args: unknown[]): Promise<unknown[]>;
  };
  preg: {
    /** First hit of /pattern/flags against subject, or null. Returns { match, groups, index }; optional groups that didn't match surface as empty strings. */
    match(arg0: string, arg1: string): unknown;
    /** Every hit of /pattern/flags against subject, as an array of { match, groups, index } objects. */
    matchAll(arg0: string, arg1: string): unknown;
    /** Substitute every match of /pattern/flags in subject. Replacement uses Go's $1 / ${1} backref syntax — PHP's \1 form is NOT translated. */
    replace(arg0: string, arg1: string, arg2: string): unknown;
  };
  preg2: {
    /** First hit of /pattern/flags via regexp2 (PCRE). Supports lookahead/lookbehind/backreferences. Same { match, groups, index } shape as preg. No linear-time guarantee. */
    match(arg0: string, arg1: string): unknown;
    /** Every hit of /pattern/flags via regexp2 (PCRE), as an array of { match, groups, index }. */
    matchAll(arg0: string, arg1: string): unknown;
    /** Substitute every match of /pattern/flags via regexp2. Replacement uses .NET $1 / ${1} syntax. Backtracking engine — keep a timeout around untrusted input. */
    replace(arg0: string, arg1: string, arg2: string): unknown;
  };
  str: {
    /** Standard base64; URL-safe input is accepted via auto-detect. */
    base64Decode(...args: unknown[]): unknown;
    /** Standard base64 (with padding). */
    base64Encode(...args: unknown[]): unknown;
    /** Inverse of nl2br: <br>, <br/>, <br /> → '\n'. */
    br2nl(...args: unknown[]): unknown;
    /** Decode named and numeric HTML entities to their UTF-8 equivalents. */
    htmlEntityDecode(...args: unknown[]): unknown;
    /** Shortcut for pad(side: 'left'). */
    lpad(...args: unknown[]): unknown;
    /** Like trim, left side only. */
    ltrim(...args: unknown[]): unknown;
    /** Replace newlines with <br> (or <br/> when xhtml=true). */
    nl2br(...args: unknown[]): unknown;
    /** Canonicalise any mix of \r\n, \r, \n to the requested style ('lf' | 'crlf' | 'cr'). */
    normalizeNewlines(...args: unknown[]): unknown;
    /** Pad to `len` with `padChar` (default ' '). `side` is 'right' (default), 'left', or 'both'. */
    pad(...args: unknown[]): unknown;
    /** sprintf + write to stdout. */
    printf(...args: unknown[]): unknown;
    /** Rune-aware reversal — `reverse('café')` is `'éfac'`. */
    reverse(...args: unknown[]): unknown;
    /** Shortcut for pad(side: 'right'). */
    rpad(...args: unknown[]): unknown;
    /** Like trim, right side only. */
    rtrim(...args: unknown[]): unknown;
    /** Go's fmt verbs (%s, %d, %x, %.2f, %v, %t, %q, …) — not PHP's. */
    sprintf(...args: unknown[]): unknown;
    /** Remove HTML tags and decode common entities. */
    stripHtml(...args: unknown[]): unknown;
    /** Strip whitespace (or any char in the optional mask string) from both ends. */
    trim(...args: unknown[]): unknown;
    /** Inverse of urlEncode. */
    urlDecode(...args: unknown[]): unknown;
    /** Form-encoding ('+' for space). For path segments use encodeURIComponent (provided by goja). */
    urlEncode(...args: unknown[]): unknown;
  };
};

/** Binary-format codecs: compression, barcodes, check digits. */
declare const codec: {
  barcode: {
    /** Available decode formats (qr / datamatrix / aztec / code128 / code39 / code93 / codabar / ean13 / ean8 / upca / upce / itf). PDF417 is encode-only. */
    decodableFormats(): string[];
    /** Decode a PNG/JPEG/WebP image to { format, text } via gozxing. Optional format hint skips the auto-detect walk. EAN/UPC need a quiet zone in the input. */
    decode(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Render data into a PNG of the chosen format. opts.width / opts.height default to 256x256 (2D) or 400x120 (1D). opts.quietZone (true or px count) pads a white margin — required for EAN/UPC to decode. */
    encode(...args: unknown[]): Promise<Uint8Array>;
    /** Available encode formats (qr / datamatrix / aztec / pdf417 / code128 / code39 / codabar / ean13 / ean8 / upca). */
    formats(): string[];
  };
  checkdigit: {
    /** Supported algorithms (luhn / isbn10 / isbn13 / ean13 / ean8 / upca). */
    algos(): string[];
    /** Compute the missing trailing check digit for a partial input. */
    compute(arg0: string, arg1: string): string;
    /** Diagnostic combining validate + compute: { valid, given, computed, … }. */
    inspect(arg0: string, arg1: string): Record<string, unknown>;
    /** Return whether the input passes the named algorithm's check digit. */
    validate(arg0: string, arg1: string): boolean;
  };
  compression: {
    /** Available compression algorithm names (gzip / deflate / zlib / bzip2 / zstd / brotli / lz4 / xz / snappy). */
    algos(): string[];
    /** Compress data with the named algorithm. Returns Uint8Array. */
    compress(...args: unknown[]): Promise<Uint8Array>;
    /** Decompress data previously produced by compress (same algorithm name required). */
    decompress(...args: unknown[]): Promise<Uint8Array>;
  };
  perl: {
    /** Perl Data::Dumper-style dump ($VAR1 = … ;), normalized indentation. JS booleans emit the JSON::XS::Boolean blessed-ref form (opts.perlBoolClass). */
    dumper(...args: unknown[]): unknown;
    /** Read Data::Dumper output back. Blessed scalar refs in the JSON bool family decode to booleans; bare 1/0 stay numbers; cycles throw. */
    parseDumper(...args: unknown[]): unknown;
  };
  php: {
    /** Best-effort read of var_dump() output. Throws on lossy markers (*RECURSION*, truncation, visibility-annotated props). */
    parseVarDump(...args: unknown[]): unknown;
    /** Read a var_export() literal (arrays, scalars, NULL, \Cls::__set_state) back to a value. */
    parseVarExport(...args: unknown[]): unknown;
    /** PHP serialize(): encode a value to PHP's canonical serialization string. Objects use the __class sentinel; cycles throw. */
    serialize(...args: unknown[]): unknown;
    /** PHP unserialize(): decode a serialize() string back to a value. r:/R: references resolve to shared objects (DAGs); cycles throw. */
    unserialize(...args: unknown[]): unknown;
    /** PHP var_dump(): human-readable debug output. String lengths are byte counts. */
    varDump(...args: unknown[]): unknown;
    /** PHP var_export(): emit valid PHP code for a value. opts.indent overrides the 2-space step. */
    varExport(...args: unknown[]): unknown;
  };
};

/** Filesystem operations: path manipulation and archive create/extract. */
declare const fs: {
  archive: {
    /** Create a zip / tar / tar.gz at destPath from a list of paths. Format inferred from extension. */
    create(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Extract a zip / tar / tar.gz to destDir. opts.overwrite controls O_EXCL behaviour. */
    extract(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  path: {
    /** Final segment of a path; optional suffix is stripped if it matches. */
    basename(...args: unknown[]): unknown;
    /** Directory portion of a path. POSIX-style; trailing slashes are stripped. */
    dirname(...args: unknown[]): unknown;
  };
};

/** Network clients and probes: HTTP, TCP/DNS/TLS/NTP/WHOIS probes, netstatus, email auth, browser-style sessions. */
declare const net: {
  browser: {
    /** Open a stateful HTTP session: { setUserAgent, setHeader, get, post, cookies }. Cookie jar + default headers persist across requests (like a browser). */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  email: {
    /** Run all five email probes in parallel — five-way handshake aggregate. */
    all(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe BIMI: TXT(<selector>._bimi.<domain>); selector defaults to 'default'. */
    bimi(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Query TXT(_dmarc.<domain>) and parse policy / pct / rua / ruf tags. */
    dmarc(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe MTA-STS: TXT(_mta-sts.<domain>) plus the fetched policy file. */
    mtaSts(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Send an outbound email: net.email.send({to, from, subject, body, html?, attachments?, headers?, server: {host, port?, auth?, tls?}, timeout?}) → Promise<{accepted: string[], rejected: [{address, reason}]}>. One TCP connection per call; per-recipient outcome captured. Transport failures throw; per-RCPT rejections surface in the result. TLS modes: starttls (default), tls, none. */
    send(...args: unknown[]): Promise<{ accepted: string[]; rejected: { address: string; reason: string }[] }>;
    /** Query TXT(<domain>) for SPF, return record + parsed mechanisms + all-policy. */
    spf(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Probe TLS-RPT: TXT(_smtp._tls.<domain>) and parse rua. */
    tlsRpt(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  http: {
    /** Perform an HTTP GET with a 5-second default timeout. Returns { status, body }. */
    get(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Perform an HTTP POST with a 5-second default timeout. Returns { status, body }. */
    post(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Full HTTP client: method, url, opts {headers, body, timeout, retry, follow, username, password}. Returns {status, ok, headers, body, url}. 4xx/5xx dont throw; retry covers transport errors + 5xx. */
    request(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  netstatus: {
    /** Run DNS / TCP / TLS / HTTP against one host concurrently. Returns { reachable, dns, tcp, tls, http } — each sub-probe ok+error; reachable = dns.ok AND tcp.ok. Sub-failures are data, not throws. */
    check(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  probe: {
    /** Look up A / AAAA / MX / TXT / CNAME / NS records. Default: all five. */
    dns(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Query an NTPv4 server (UDP 123) and report offset, RTT, stratum, root delay / dispersion. */
    ntp(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Reachability probe. mode tcp (default; dials host:port) or icmp (needs raw-socket privileges). Returns { sent, received, lossPercent, minMs, avgMs, maxMs }. Unreachable = received 0, no throw. */
    ping(...args: unknown[]): Promise<{ host: string; ip: string; mode: string; sent: number; received: number; lossPercent: number; minMs: number; avgMs: number; maxMs: number }>;
    /** SMTP capability probe (no mail sent). EHLO + parse extensions. Returns { banner, ehloDomain, extensions, starttls, authMechanisms, sizeLimit }. Connection failures throw. */
    smtp(...args: unknown[]): Promise<{ host: string; port: string; banner: string; ehloDomain: string; extensions: string[]; starttls: boolean; authMechanisms: string[]; sizeLimit: number }>;
    /** Dial a TCP target and report latency + resolved IP. Default timeout 5s. */
    tcp(...args: unknown[]): Promise<{ host: string; port: number; ip: string; latencyMs: number }>;
    /** Open a TLS connection (InsecureSkipVerify; for probing only) and return the cert chain summary. */
    tls(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Two-hop WHOIS via the IANA referral, returning the parsed record plus the raw response text. */
    whois(...args: unknown[]): Promise<Record<string, unknown>>;
    /** WebSocket handshake probe. Opens ws://wss:// connection, optional ping/pong RTT. Returns { connected, subprotocol, status, handshakeMs, pingMs }. Failed handshake throws. */
    wss(...args: unknown[]): Promise<{ url: string; connected: boolean; subprotocol: string; status: number; handshakeMs: number; pingMs: number }>;
  };
};

/** Database / KV / directory clients: SQLite, PostgreSQL, MySQL/MariaDB, SQL Server, Redis, memcached, LDAP, dict. */
declare const db: {
  clickhouse: {
    /** Connect to ClickHouse via the pure-Go clickhouse-go v2 driver. Arg is a clickhouse:// URL DSN string or an options object { host, port, user, password, database, secure }. Returns the shared SQL handle { exec, query, queryValue, begin, prepare, close }. Uses ? placeholders; default native port 9000 (set secure:true for TLS). Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  dict: {
    /** RFC 2229 DICT word lookup. define(host, word, opts?) -> { word, found, definitions: [{ db, dbName, text }] }. found:false on no match (not an error). */
    define(...args: unknown[]): Promise<{ word: string; found: boolean; definitions: { db: string; dbName: string; text: string }[] }>;
    /** RFC 2229 word match. match(host, word, opts?) -> { word, matches: [{ db, word }] }. opts.strategy (default prefix), opts.database, opts.port (default 2628). */
    match(...args: unknown[]): Promise<{ word: string; matches: { db: string; word: string }[] }>;
  };
  ldap: {
    /** Dial LDAP (ldap://host:port), anonymous bind (or opts.bindDN/password). Returns { rootDSE, search, close }. search(baseDN, filter, attrs?) -> entries; rootDSE -> server metadata. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  memcached: {
    /** Connect to memcached (host:port). Returns { get, set, delete }. get -> string or null (miss); delete -> bool (existed). set(key, value, expirySeconds?). */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  mssql: {
    /** Connect to Microsoft SQL Server via the pure-Go go-mssqldb driver. Arg is a sqlserver:// URL DSN string or an options object { host, port, user, password, database }. Returns the shared SQL handle. Uses @p1,@p2,… placeholders. Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  mysql: {
    /** Connect to MySQL/MariaDB via the pure-Go go-sql-driver. Arg is a go-sql-driver DSN string (user:pass@tcp(host:port)/db) or an options object { host, port, user, password, database }. Returns the shared SQL handle. Uses ? placeholders. Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  oracle: {
    /** Connect to Oracle via the pure-Go go-ora driver (no cgo). Arg is an oracle:// URL DSN string or an options object { host, port, user, password, database } where database is the service name. Returns the shared SQL handle. Uses :1,:2,… bind placeholders; default port 1521. Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  postgres: {
    /** Connect to PostgreSQL via the pure-Go pgx driver. Arg is a libpq DSN/URL string or an options object { host, port, user, password, database, sslmode }. Returns the shared SQL handle { exec, query, queryValue, begin, prepare, close }. Uses $1,$2,… placeholders. Pings on open. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  redis: {
    /** Connect to Redis (redis://...). Returns { do, ping, close }. do(cmd, ...args) runs any RESP command; missing key -> null. Pings on open to surface bad addresses. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  sqlite: {
    /** Open a SQLite database (':memory:' or a file path; created if absent). Resolves to a handle { exec, query, queryValue, begin, prepare, close }. Connection is Ping-ed before resolving. */
    open(...args: unknown[]): Promise<Record<string, unknown>>;
  };
};

/** Subprocess and external-CLI / service wrappers: shell, git, gh, AI providers. */
declare const services: {
  ai: {
    /** Which of claude / codex / copilot / gemini are on PATH, in preference order. */
    providers(): string[];
    /** Run a one-shot prompt through a provider. opts { prompt (required), provider?, system?, context?, timeout? }. Returns { provider, output, exitCode }. Non-zero exit is data; no provider throws. */
    send(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  exec: {
    /** HTTP via recon (preferred) or curl (fallback). 4xx / 5xx resolve as status; transport errors and timeouts throw. opts.backend = 'auto' | 'recon' | 'curl'. */
    http(...args: unknown[]): Promise<Record<string, unknown>>;
    /** Run a subprocess. String cmd → /bin/sh -c (or `cmd /C` on Windows); array cmd → argv. Non-zero exits resolve; spawn failures and timeouts throw. */
    shell(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  gh: {
    /** Probe gh's auth state. Missing gh / unauthenticated resolve with { authenticated: false, … } — only context cancellation throws. */
    authStatus(...args: unknown[]): Promise<{ authenticated: boolean; user: string; raw: string }>;
    /** List pull requests on the cwd's repo (or opts.cwd). Defaults: open state, limit 30. Filters: state / limit / author. */
    prList(...args: unknown[]): Promise<Record<string, unknown>[]>;
    /** Repo metadata. With no arg uses cwd's repo; pass 'owner/name' for any repo gh can see. owner + defaultBranch are pre-flattened. */
    repoView(...args: unknown[]): Promise<Record<string, unknown>>;
  };
  git: {
    /** Stage one path (string) or several (string[]). */
    add(...args: unknown[]): Promise<{ paths: string[] }>;
    /** Current branch (empty when HEAD is detached) plus the list of local branches. */
    branch(...args: unknown[]): Promise<{ current: string; detached: boolean; all: string[] }>;
    /** Create a commit; returns the post-commit HEAD SHA. opts.allowEmpty toggles --allow-empty. */
    commit(...args: unknown[]): Promise<{ sha: string }>;
    /** Aggregate { files, insertions, deletions } from `git diff --shortstat`. Default revRange HEAD~1..HEAD. */
    diffStat(...args: unknown[]): Promise<{ files: number; insertions: number; deletions: number }>;
    /** True iff `git status --porcelain` is empty. */
    isClean(...args: unknown[]): Promise<boolean>;
    /** Recent commits as { sha, shortSha, author, email, timestamp, subject }. opts.limit / opts.revRange. */
    log(...args: unknown[]): Promise<{ sha: string; shortSha: string; author: string; email: string; timestamp: number; subject: string }[]>;
    /** Full 40-char SHA for the given rev. Invalid refs throw. */
    revParse(...args: unknown[]): Promise<string>;
    /** Escape hatch: run any `git <args>`, get { stdout, stderr, exitCode } — exitCode is data, not a throw. */
    runText(...args: unknown[]): Promise<{ stdout: string; stderr: string; exitCode: number }>;
    /** Parsed `git status --porcelain` entries: { path, indexStatus, workingStatus }. */
    status(...args: unknown[]): Promise<{ path: string; indexStatus: string; workingStatus: string }[]>;
  };
};

/** Multi-pane terminal UI: layout, pane, write, focus. */
declare const tui: {
  /** Declare the pane layout for this Run. Tree nodes: { name, title?, weight? } (leaf), { rows: [...], weight? } (vertical split), { cols: [...], weight? } (horizontal split). Throws on duplicate names, empty rows/cols, unknown keys, or under --watch. */
  layout(...args: unknown[]): unknown;
  /** Return a Pane handle for a declared pane. Throws if the name wasn't in the layout. Handle methods: write(text), writeln(text), clear(), title(text). services.exec.shell({pane}) streams subprocess I/O into a pane. */
  pane(...args: unknown[]): unknown;
};

/** Network servers: HTTP/HTTPS listeners with routing, middleware, static files, WebSocket upgrade. */
declare const server: {
  http: {
    /** Bind an HTTP listener: server.http.listen({port, host?, routes, use?}) → handle with .address, .close(), .stopped Promise. routes is a map of stdlib http.ServeMux patterns ('GET /users/{id}') to handlers (req, res) => res.json({...}) or {use: [...], handler: fn} for per-route middleware. Handlers can call res.upgradeWebSocket(opts?) to hijack the connection and return an AsyncIterable<WSMessage> with .send / .close — `for await (const msg of ws)` walks frames; msg is {type:'text',text} or {type:'binary',bytes:Uint8Array}. */
    listen(...args: unknown[]): unknown;
    /** Static-file mount: server.http.static({dir, stripPrefix, index?, etag?}) → handler. Assign to a wildcard route (GET /assets/{rest...}). Internally stdlib http.FileServer with stripPrefix; ETag/Last-Modified/range requests work; no directory listing. */
    static(...args: unknown[]): unknown;
  };
  https: {
    /** Like server.http.listen plus required cert/key (file paths OR inline PEM strings). No autocert; no self-signed magic. */
    listen(...args: unknown[]): unknown;
    /** Like server.http.static; same options. */
    static(...args: unknown[]): unknown;
  };
  smtp: {
    /** Bind an SMTP listener: server.smtp.listen({port, hostname?, handlers: {onMail, onRcpt, onData}, auth?, starttls?, allowInsecureAuth?, maxMessageBytes?, maxRecipients?, sessionTimeout?}) → handle with .address, .close(), .stopped Promise. Handlers receive (envelope, …) per stage; return true/undefined to accept, false to reject, a string for a 550 reason, throw for 451 temp-fail. onData receives a parsed Message with text/html bodies, attachments, and raw bytes. */
    listen(...args: unknown[]): unknown;
  };
};

